// --- MVP Concepts Data ---
// Added canEvolve flag (boolean) to concepts that might branch later
const concepts = [
    // ... (Most concepts remain the same, add canEvolve: true where appropriate)
    { id: 1, name: "Heterosexual", type: "Orientation", primaryElement: "A", elementScores: {Attraction:5, Interaction:5, Sensory:5, Psychological:5, Cognitive:5, Relational:5}, relatedIds: [7, 39], canEvolve: false },
    // ...
    { id: 20, name: "BDSM", type: "Framework", primaryElement: "I", elementScores: {Attraction:6, Interaction:7, Sensory:7, Psychological:7, Cognitive:7, Relational:6}, relatedIds: [12, 13, 14, 18, 21, 22, 23, 24, 25, 35], canEvolve: true }, // Can branch into specifics
    { id: 21, name: "Power Exchange", type: "Practice", primaryElement: "I", elementScores: {Attraction:5, Interaction:8, Sensory:6, Psychological:8, Cognitive:7, Relational:6}, relatedIds: [12, 13, 20, 36, 37, 35], canEvolve: true }, // Could branch into M/s, D/s etc.
    { id: 22, name: "Spanking", type: "Practice", primaryElement: "S", elementScores: {Attraction:5, Interaction:7, Sensory:8, Psychological:6, Cognitive:4, Relational:5}, relatedIds: [20, 12, 13, 36, 37], canEvolve: true }, // Could branch into implements
    { id: 25, name: "Rope Play", type: "Practice", primaryElement: "S", elementScores: {Attraction:5, Interaction:7, Sensory:7, Psychological:7, Cognitive:6, Relational:5}, relatedIds: [20, 24, 35], canEvolve: true }, // Could branch to Shibari etc.
    { id: 29, name: "Role Playing", type: "Practice", primaryElement: "C", elementScores: {Attraction:6, Interaction:6, Sensory:5, Psychological:6, Cognitive:9, Relational:6}, relatedIds: [18, 30, 38], canEvolve: true }, // Could branch into specific scenarios
    // ... (Mark others as canEvolve: false or true as appropriate) ...
    { id: 41, name: "Emotional Connection Focus", type: "Approach", primaryElement: "P", elementScores: {Attraction:5, Interaction:4, Sensory:4, Psychological:9, Cognitive:5, Relational:4}, relatedIds: [5, 6, 7, 17, 34, 40], canEvolve: false }
];
// --- Rest of data.js (elementKeyToName, elementExplanations, questionnaireGuided) remains the same ---
const elementKeyToName = { A: "Attraction", I: "Interaction", S: "Sensory", P: "Psychological", C: "Cognitive", R: "Relational" };
const elementExplanations = { "Attraction": "Relates to the 'Who' or 'What' primarily draws your sexual interest...", "Interaction": "Describes the 'How' - your preferred dynamic...", "Sensory": "Focuses on the 'Feel' - the types and intensity of physical sensations...", "Psychological": "Explores the 'Why' - the core emotional or psychological needs...", "Cognitive": "Concerns the 'Mind' - the role and importance of fantasy, intellect...", "Relational": "Defines the 'With Whom' structure - your preferred context..." };
const questionnaireGuided = { /* ... Same structure as before ... */
    "Attraction": [ { qId: "G_Attr1", text: "Is a strong emotional bond necessary before sexual attraction develops?", type: "radio", options: [{ value: "Yes", points: -2 }, { value: "Sometimes", points: 0 }, { value: "No", points: 1 }], scoreWeight: 1.5 }, { qId: "G_Attr2", text: "How broad is the range of genders/presentations you *could* be attracted to?", type: "slider", minLabel: "Very Specific", maxLabel: "Very Broad", minValue: 0, maxValue: 10, defaultValue: 5, scoreWeight: 1.0 }, { qId: "G_Attr3", text: "Are specific objects, materials, or situations a significant focus of your arousal?", type: "radio", options: [{ value: "Yes", points: 1 }, { value: "Sometimes", points: 0 }, { value: "Rarely/No", points: -1 }], scoreWeight: 0.5 } ],
    "Interaction": [ { qId: "G_Inter1", text: "Preferred dynamic lean:", type: "slider", minLabel: "Submitting/Following", maxLabel: "Dominating/Leading", minValue: 0, maxValue: 10, defaultValue: 5, scoreWeight: 1.5 }, { qId: "G_Inter2", text: "Which energies also appeal? (Choose up to 2)", type: "checkbox", options: [{ value: "Playful", points: 0.5 }, { value: "Nurturing/Caring", points: -0.5 }, { value: "Service-Oriented", points: -0.5 }, { value: "Performance/Exhibition", points: 0.5 }], scoreWeight: 1.0, maxChoices: 2 } ],
    "Sensory": [ { qId: "G_Sens1", text: "Importance of intense sensation?", type: "slider", minLabel: "Low", maxLabel: "High", minValue: 0, maxValue: 10, defaultValue: 5, scoreWeight: 1.0 }, { qId: "G_Sens2", text: "Leaning towards Pleasure vs Pain/Intensity?", type: "radio", options: [{ value: "Strongly Pleasure", points: -2 }, { value: "Mostly Pleasure", points: -1 }, { value: "Mix/Depends", points: 0 }, { value: "Mostly Pain/Intensity", points: 1 }, { value: "Strongly Pain/Intensity", points: 2 }], scoreWeight: 1.0 } ],
    "Psychological": [ { qId: "G_Psych1", text: "Select your top 2 primary emotional drivers:", type: "checkbox", options: [{ value: "Intimacy/Connection", points: 2 }, { value: "Power/Control", points: 1 }, { value: "Surrender/Release", points: 1 }, { value: "Playfulness/Fun", points: 0 }, { value: "Validation/Admiration", points: 0 }, { value: "Comfort/Security", points: -1 }, { value: "Escape/Transcendence", points: 0 }], scoreWeight: 1.5, maxChoices: 2 }, { qId: "G_Psych2", text: "How important is 'Trust' in your sexual experiences?", type: "slider", minLabel: "Not Vital", maxLabel: "Essential", minValue: 0, maxValue: 10, defaultValue: 7, scoreWeight: 0.5 } ],
    "Cognitive": [ { qId: "G_Cog1", text: "Importance of mental stimulation (fantasy, scenarios)?", type: "slider", minLabel: "Low", maxLabel: "High", minValue: 0, maxValue: 10, defaultValue: 5, scoreWeight: 1.5 }, { qId: "G_Cog2", text: "Preferred cognitive style?", type: "radio", options: [{ value: "Present/Embodied", points: -1 }, { value: "Fantasy/Scenario Driven", points: 1 }, { value: "Intellectual/Psychological Play", points: 1 }, { value: "Varies Greatly", points: 0 }], scoreWeight: 0.5 } ],
    "Relational": [ { qId: "G_Rel1", text: "Preference for Exclusivity vs Openness?", type: "slider", minLabel: "Strictly Exclusive", maxLabel: "Very Open", minValue: 0, maxValue: 10, defaultValue: 5, scoreWeight: 1.5 }, { qId: "G_Rel2", text: "Importance of partner familiarity?", type: "radio", options: [{ value: "Essential (Known Partners)", points: -1 }, { value: "Preferred but Flexible", points: 0 }, { value: "Anonymity/Casual is Fine/Preferred", points: 1 }], scoreWeight: 0.5 } ]
};
