// data.js - Centralized Game Data
// Ensure this file is loaded first or its exports are available when needed

console.log("data.js starting..."); // Log for debugging load order

// --- Core Element Definitions ---
const elementDetails = {
    "Attraction": {
        name: "Attraction Focus",
        coreQuestion: "Who or What sparks your sexual interest and arousal?",
        coreConcept: "Defines the primary target, nature, or conditions for sexual attraction, beyond simple orientation.",
        elaboration: "Includes orientation (hetero-, homo-, bi-, pan-, a-, demi-), specific aesthetics, dynamics, concepts, objects, situations, or required connection levels.",
        scoreInterpretations: {
            "Very Low": "Suggests very little specific sexual attraction (Asexual leaning).",
            "Low": "Attraction might be infrequent, require strong bonds (Demisexual leaning), or be primarily responsive.",
            "Moderate": "Attraction towards familiar cues (gender/presentation), potentially broad.",
            "High": "Strong focus towards particular targets, dynamics, or specific objects/situations (fetishistic interests).",
            "Very High": "Very strong, potentially primary, focus on specific triggers (intense orientation or strong fetishistic/paraphilic focus)."
        },
        examples: "Asexuality, Demisexuality, Heterosexuality, Homosexuality, Bisexuality, Pansexuality, Sapiosexuality, Fetishes (latex, feet, uniforms), D/s roles.",
        personaConnection: "Defines the fundamental 'object' or condition of your sexual desire."
    },
    "Interaction": {
        name: "Interaction Style",
        coreQuestion: "How do you prefer to engage and exchange energy during sexual encounters?",
        coreConcept: "Describes preferred behavioral dynamics, roles, and energy flow in sexual interaction.",
        elaboration: "Covers leading vs. following, collaboration vs. power differentials, nurturing, service, playfulness, performance. Linked to identities like Dom/Sub, Top/Bottom.",
        scoreInterpretations: {
            "Very Low": "Strong preference for yielding control, following direction, serving (Strongly Submissive leaning).",
            "Low": "Prefers letting others lead, supportive roles, receiving (Submissive or Bottom leaning).",
            "Moderate": "Prefers collaborative, egalitarian dynamics, mutual give-and-take, potentially switching roles.",
            "High": "Enjoys initiative, guiding, providing sensation/care, being center of attention (Dominant, Top, or Caregiver leaning).",
            "Very High": "Strong preference or need to be in control, direct, command (Strongly Dominant role)."
        },
        examples: "Dominance/submission (D/s), Master/slave (M/s), Top/Bottom/Versatile, Primal play, Service, Exhibitionism/Voyeurism, Teacher/student, Caregiver/Little.",
        personaConnection: "Defines your preferred social and power 'dance' within sexuality."
    },
    "Sensory": {
        name: "Sensory Emphasis",
        coreQuestion: "What physical Feelings are most important or sought after?",
        coreConcept: "Relates to the significance, type, and intensity of physical sensations in arousal and fulfillment.",
        elaboration: "Encompasses touch (light, firm, impact), temperature, texture, pressure (binding), vibration, internal sensations, visual, auditory, olfactory input. Includes pleasure/pain spectrum (Sadomasochism).",
        scoreInterpretations: {
            "Very Low": "Physical sensation secondary or unimportant compared to emotional/psychological/cognitive aspects.",
            "Low": "Prefers subtle, gentle, 'vanilla' sensations. Comfort, warmth prioritized.",
            "Moderate": "Enjoys broad range of conventional sensations, open to mild intensity.",
            "High": "Actively seeks distinct, strong, or specific physical input (impact, temperature, texture, light restriction).",
            "Very High": "Strongly driven by or requires intense, specific, or extreme sensations (heavy impact, needles, wax, intense restriction, sensory deprivation/overload)."
        },
        examples: "Massage, kissing, cuddling, BDSM impact (flogging, caning), wax play, ice play, rope bondage, Shibari, sensory deprivation, electrostimulation, material fetishes (feel).",
        personaConnection: "Defines how your body interfaces with sexuality and what physical input it craves or avoids."
    },
    "Psychological": {
        name: "Psychological Driver",
        coreQuestion: "Why do you engage with sexuality? What underlying needs does it fulfill?",
        coreConcept: "Explores core emotional, psychological, or existential motivations, needs, and states sexuality helps access or satisfy.",
        elaboration: "Includes needs for connection (intimacy, trust, vulnerability), power dynamics (control, surrender, objectification), self-expression (validation, exploration), state change (escape, transcendence, catharsis), and comfort.",
        scoreInterpretations: {
            "Very Low": "Sexuality primarily physical or recreational. Deep needs met elsewhere.",
            "Low": "Emotional/psychological aspects present but secondary (fun, release, light connection).",
            "Moderate": "Balanced fulfillment of connection, stress relief, fun, validation.",
            "High": "Sexuality is a significant channel for fulfilling specific core psychological needs (Intimacy, Power, Validation, Catharsis).",
            "Very High": "Fulfilling profound psychological needs is the primary driver (total surrender, absolute control, deep vulnerability, transcendence)."
        },
        examples: "Stress relief focus, seeking deep intimacy, BDSM for catharsis/power exchange, seeking validation through performance, using intensity for transcendence.",
        personaConnection: "Defines the emotional and motivational core of your sexual expression – its deeper purpose."
    },
    "Cognitive": {
        name: "Cognitive Engagement",
        coreQuestion: "How important is the Mind – fantasy, intellect, scenarios – in your arousal?",
        coreConcept: "Measures the degree and style of mental involvement preferred or required.",
        elaboration: "Contrasts focus on immediate presence with reliance on imagination, narrative, psychological complexity, or intellectual stimulation. Includes fantasy, role-play, mind games, banter.",
        scoreInterpretations: {
            "Very Low": "Strong preference for being present/embodied. Finds fantasy/analysis distracting.",
            "Low": "Primarily enjoys immediate experience. Minimal mental constructs.",
            "Moderate": "Appreciates some mental engagement (occasional role-play, dirty talk, understanding dynamics), but not reliant.",
            "High": "Arousal significantly enhanced by mental elements (detailed fantasy, role-play, power dynamics analysis, banter).",
            "Very High": "Deeply reliant on the mind (intricate scenarios, world-building, complex mind games, conceptual focus)."
        },
        examples: "Mindful touch (Low), dirty talk descriptions (Moderate), D/s protocol scenes (High/Very High), fantasy LARP sex (High/Very High), erotica (High/Very High), psychological edge play (Very High).",
        personaConnection: "Defines how much and in what way your thoughts and imagination participate."
    },
    "Relational": {
        name: "Relational Context",
        coreQuestion: "In what Structure or with whom do you ideally express your sexuality?",
        coreConcept: "Describes preferred social structure and context for sexual relationships.",
        elaboration: "Considers number of partners, commitment/intimacy levels, familiarity vs. anonymity, dyadic vs. group interactions. Covers solitary, monogamy, and consensual non-monogamy (CNM).",
        scoreInterpretations: {
            "Very Low": "Strong preference for solitary expression or strictly exclusive lifelong partnership.",
            "Low": "Prefers/seeks monogamous, committed relationships. Casual less appealing.",
            "Moderate": "Comfortable with committed dyads, potentially open to some flexibility (swinging, casual dating) or values connection without strict exclusivity (Solo Poly exploring CNM).",
            "High": "Prefers/practices structures involving multiple partners or explicit openness (Open Relationships, Polyamory).",
            "Very High": "Strong preference for highly fluid, non-traditional structures (Relationship Anarchy, non-hierarchical Polyamory, group dynamics, varied commitment/anonymity)."
        },
        examples: "Masturbation, Serial Monogamy, Lifelong Monogamy, FWB, Open Relationships, Swinging, Triads/Quads, Polyamory (Hierarchical, Egalitarian, Solo), Relationship Anarchy, Group Sex, Anonymous Encounters.",
        personaConnection: "Defines the preferred social constellation (or lack thereof) for your sexual life."
    }
};

// --- Concepts Data (with Keywords added) ---
const concepts = [
    // --- Common Concepts (~40) ---
    { id: 1, name: "Vanilla Sex", cardType: "Practice/Kink", visualHandle: "common_vanilla", primaryElement: "S", elementScores: { A: 5, I: 5, S: 3, P: 4, C: 3, R: 4 }, briefDescription: "Conventional sexual activity.", detailedDescription: "Refers to sexual expression generally considered within conventional norms, often focused on penile-vaginal intercourse or mutual masturbation without specific power dynamics, intense sensations, or elaborate scenarios.", relatedIds: [2, 3, 33], rarity: 'common', canUnlockArt: false, keywords: ['Conventional', 'Standard', 'Mainstream', 'Physical', 'Simple', 'Intercourse'] },
    { id: 2, name: "Sensual Touch", cardType: "Practice/Kink", visualHandle: "common_sensual", primaryElement: "S", elementScores: { A: 4, I: 4, S: 4, P: 5, C: 2, R: 4 }, briefDescription: "Gentle, affectionate touch.", detailedDescription: "Focus on gentle, affectionate, and pleasurable touch, emphasizing connection, warmth, and non-goal-oriented physical intimacy. Can include massage, caressing, holding.", relatedIds: [1, 15, 31, 3, 80, 102], rarity: 'common', canUnlockArt: true, visualHandleUnlocked: "common_sensual_art", keywords: ['Gentle', 'Affection', 'Connection', 'Sensation', 'Comfort', 'Touch', 'Massage', 'Caress'] },
    { id: 3, name: "Passionate Kissing", cardType: "Practice/Kink", visualHandle: "common_kissing", primaryElement: "S", elementScores: { A: 6, I: 5, S: 5, P: 6, C: 3, R: 5 }, briefDescription: "Intense, emotional kissing.", detailedDescription: "Intense and emotionally charged kissing as a primary form of connection and arousal. Can range from deep and lingering to urgent and demanding.", relatedIds: [1, 2, 15, 47, 66, 85], rarity: 'common', canUnlockArt: false, keywords: ['Kissing', 'Intensity', 'Emotion', 'Connection', 'Sensation', 'Intimacy', 'Mouth'] },
    { id: 4, name: "Dominance (Psychological)", cardType: "Identity/Role", visualHandle: "uncommon_dom", primaryElement: "I", elementScores: { A: 6, I: 9, S: 5, P: 8, C: 7, R: 6 }, briefDescription: "Taking psychological control.", detailedDescription: "Focuses on the mental and emotional aspects of control within a dynamic, potentially involving commands, tasks, setting rules, or managing a partner's experience.", relatedIds: [5, 6, 11, 30, 38, 81, 89, 90, 100, 104, 109, 123], rarity: 'uncommon', canUnlockArt: true, visualHandleUnlocked: "uncommon_dom_art", keywords: ['Dominance', 'Dom', 'Control', 'Power', 'Leading', 'Psychological', 'Rules', 'Structure', 'Mental'] },
    { id: 5, name: "Submission (Psychological)", cardType: "Identity/Role", visualHandle: "uncommon_sub", primaryElement: "I", elementScores: { A: 6, I: 1, S: 5, P: 8, C: 5, R: 6 }, briefDescription: "Yielding psychological control.", detailedDescription: "Focuses on the mental and emotional aspects of yielding control, finding pleasure or fulfillment in obedience, service, following directions, or surrendering decisions.", relatedIds: [4, 6, 17, 10, 12, 37, 39, 58, 61, 63, 87, 91, 98, 99, 109, 119, 123], rarity: 'uncommon', canUnlockArt: true, visualHandleUnlocked: "uncommon_sub_art", keywords: ['Submission', 'Sub', 'Surrender', 'Power', 'Following', 'Psychological', 'Obedience', 'Trust', 'Vulnerability', 'Yielding'] },
    { id: 6, name: "Switching", cardType: "Identity/Role", visualHandle: "uncommon_switch", primaryElement: "I", elementScores: { A: 6, I: 5, S: 6, P: 7, C: 6, R: 6 }, briefDescription: "Moving between D/s roles.", detailedDescription: "Describes the ability and desire to fluidly shift between dominant and submissive roles or energies within sexual encounters, enjoying aspects of both leading and following.", relatedIds: [4, 5], rarity: 'uncommon', canUnlockArt: false, keywords: ['Switch', 'Fluidity', 'Power', 'Interaction', 'Versatility', 'Role', 'D/s', 'BDSM'] },
    { id: 7, name: "Impact Play (Light)", cardType: "Practice/Kink", visualHandle: "uncommon_impact_light", primaryElement: "S", elementScores: { A: 5, I: 6, S: 6, P: 5, C: 4, R: 5 }, briefDescription: "Spanking, light slapping/flogging.", detailedDescription: "Involves activities like spanking, slapping, or using paddles/floggers lightly, primarily for pleasurable stinging sensations or rhythmic input rather than intense pain.", relatedIds: [8, 9, 4, 5, 40, 57, 93, 96], rarity: 'uncommon', canUnlockArt: true, visualHandleUnlocked: "uncommon_impact_light_art", keywords: ['Impact', 'Spanking', 'Slapping', 'Paddle', 'Flogger', 'Sensation', 'Physical', 'Playful', 'Rhythm', 'BDSM'] },
    { id: 8, name: "Impact Play (Heavy)", cardType: "Practice/Kink", visualHandle: "rare_impact_heavy", primaryElement: "S", elementScores: { A: 5, I: 7, S: 9, P: 7, C: 4, R: 6 }, briefDescription: "Intense impact, pain/marks focus.", detailedDescription: "Utilizes implements like canes, whips, heavy paddles, or fists to deliver strong, often painful sensations. Focus can be on endurance, marking, or the psychological aspects of receiving intense impact.", relatedIds: [7, 9, 4, 5, 44, 97, 110], rarity: 'rare', canUnlockArt: true, visualHandleUnlocked: "rare_impact_heavy_art", uniquePromptId: "rP08", keywords: ['Impact', 'Pain Play', 'Intensity', 'Sensation', 'Endurance', 'Marking', 'Control', 'Cane', 'Whip', 'BDSM', 'Heavy'] },
    { id: 9, name: "Pain Play (Non-Impact)", cardType: "Practice/Kink", visualHandle: "rare_pain", primaryElement: "S", elementScores: { A: 4, I: 6, S: 8, P: 7, C: 5, R: 6 }, briefDescription: "Pinching, biting, wax, needles.", detailedDescription: "Focuses on creating intense sensations through means other than direct impact, such as pinching, biting, scratching, temperature play (wax, ice), clamps, or potentially needles (use extreme caution).", relatedIds: [7, 8, 16, 17, 37, 44, 63, 88, 96, 97, 110, 111, 112, 106, 124], rarity: 'rare', canUnlockArt: true, visualHandleUnlocked: "rare_pain_art", uniquePromptId: "rP09", keywords: ['Pain Play', 'Sensation', 'Intensity', 'Focus', 'Body Modification', 'Edge', 'Pinch', 'Bite', 'Scratch', 'Wax', 'Ice', 'Clamps', 'Needles', 'BDSM'] },
    { id: 10, name: "Service Submission", cardType: "Psychological/Goal", visualHandle: "uncommon_service", primaryElement: "I", elementScores: { A: 5, I: 2, S: 4, P: 7, C: 4, R: 6 }, briefDescription: "Pleasure from serving a partner.", detailedDescription: "A form of submission focused on deriving pleasure and fulfillment from performing acts of service for a partner, which may be sexual or non-sexual within a dynamic.", relatedIds: [5, 4, 11, 58, 61, 98, 109], rarity: 'uncommon', canUnlockArt: false, keywords: ['Service', 'Submission', 'Sub', 'Psychological', 'Devotion', 'Power', 'Act', 'Serving', 'BDSM'] },
    { id: 11, name: "Command/Control Dynamics", cardType: "Psychological/Goal", visualHandle: "rare_control", primaryElement: "I", elementScores: { A: 6, I: 9, S: 5, P: 8, C: 8, R: 6 }, briefDescription: "Explicit orders given/obeyed.", detailedDescription: "A power dynamic characterized by one partner giving clear commands or instructions and the other partner deriving pleasure or fulfillment from obeying them precisely.", relatedIds: [4, 5, 10, 30, 38, 45, 41, 89, 90, 100, 101, 109, 119, 120], rarity: 'rare', canUnlockArt: true, visualHandleUnlocked: "rare_control_art", uniquePromptId: "rP11", keywords: ['Control', 'Command', 'Obedience', 'Power', 'Structure', 'Psychological', 'Interaction', 'Dom', 'Sub', 'Order', 'BDSM'] },
    { id: 12, name: "Objectification Play", cardType: "Psychological/Goal", visualHandle: "rare_object", primaryElement: "P", elementScores: { A: 7, I: 4, S: 6, P: 8, C: 6, R: 5 }, briefDescription: "Consensually treating/being treated as object.", detailedDescription: "Consensual play involving focusing on a person's body or specific body parts as the primary source of pleasure or utility, potentially dehumanizing them temporarily within the agreed scene.", relatedIds: [4, 5, 20, 18, 19, 45, 61, 42, 62, 114], rarity: 'rare', canUnlockArt: false, uniquePromptId: "rP12", keywords: ['Objectification', 'Power', 'Psychological', 'Focus', 'Body', 'Dehumanization', 'Use', 'Thing', 'BDSM'] },
    { id: 13, name: "Role-Playing (Scenario)", cardType: "Practice/Kink", visualHandle: "uncommon_roleplay", primaryElement: "C", elementScores: { A: 6, I: 6, S: 5, P: 6, C: 8, R: 6 }, briefDescription: "Adopting characters/personas.", detailedDescription: "Involves adopting specific character archetypes (e.g., doctor/patient, teacher/student, captor/captive) or personas to create a narrative framework for sexual interaction.", relatedIds: [14, 30, 21, 39, 64, 92, 98, 101, 117, 121, 43], rarity: 'uncommon', canUnlockArt: true, visualHandleUnlocked: "uncommon_roleplay_art", keywords: ['Role-Play', 'Roleplay', 'Cognitive', 'Fantasy', 'Scenario', 'Character', 'Persona', 'Acting', 'Scene'] },
    { id: 14, name: "Fantasy Immersion", cardType: "Cognitive", visualHandle: "rare_fantasy", primaryElement: "C", elementScores: { A: 5, I: 3, S: 4, P: 7, C: 9, R: 3 }, briefDescription: "Deep focus on internal narrative.", detailedDescription: "Prioritizes internal mental experience, elaborate fantasy worlds, or complex narratives over external reality during sexual encounters. Arousal is heavily dependent on the mental construct.", relatedIds: [13, 29, 41, 42, 49], rarity: 'rare', canUnlockArt: true, visualHandleUnlocked: "rare_fantasy_art", uniquePromptId: "rP14", keywords: ['Fantasy', 'Cognitive', 'Immersion', 'Narrative', 'Mind', 'World-Building', 'Imagination', 'Mental'] },
    { id: 15, name: "Deep Emotional Intimacy", cardType: "Psychological/Goal", visualHandle: "uncommon_intimacy", primaryElement: "P", elementScores: { A: 7, I: 5, S: 4, P: 9, C: 5, R: 7 }, briefDescription: "Seeking profound connection.", detailedDescription: "Places a high value on using sexual expression as a way to build and deepen emotional connection, trust, vulnerability, and mutual understanding.", relatedIds: [2, 3, 22, 29, 47, 58, 68, 70, 75, 76, 82, 83, 123, 59], rarity: 'uncommon', canUnlockArt: true, visualHandleUnlocked: "uncommon_intimacy_art", keywords: ['Intimacy', 'Connection', 'Vulnerability', 'Trust', 'Emotion', 'Psychological', 'Deep', 'Bonding'] },
    { id: 16, name: "Rope Bondage (Shibari/Kinbaku)", cardType: "Practice/Kink", visualHandle: "rare_rope", primaryElement: "S", elementScores: { A: 6, I: 7, S: 8, P: 7, C: 6, R: 6 }, briefDescription: "Aesthetic/restrictive rope tying.", detailedDescription: "An art form and practice involving tying a partner with rope, focusing on aesthetic patterns, nerve pressure, physical restriction, and the psychological state induced by the tie.", relatedIds: [9, 17, 4, 5, 44, 87, 101, 113], rarity: 'rare', canUnlockArt: true, visualHandleUnlocked: "rare_rope_art", uniquePromptId: "rP16", keywords: ['Rope', 'Bondage', 'Shibari', 'Kinbaku', 'Restriction', 'Sensation', 'Aesthetic', 'Control', 'Trust', 'Helplessness', 'Tying', 'Art', 'BDSM'] },
    { id: 17, name: "Restriction/Helplessness", cardType: "Psychological/Goal", visualHandle: "rare_restrict", primaryElement: "P", elementScores: { A: 5, I: 3, S: 7, P: 9, C: 5, R: 5 }, briefDescription: "Arousal from restraint/surrender.", detailedDescription: "Deriving significant arousal from the sensation of being physically restrained (via ropes, cuffs, etc.) and the associated psychological state of helplessness or surrender.", relatedIds: [16, 5, 9, 37, 44, 63, 64, 87, 99, 113, 117, 118, 125, 43], rarity: 'rare', canUnlockArt: false, uniquePromptId: "rP17", keywords: ['Restriction', 'Helplessness', 'Surrender', 'Restraint', 'Bondage', 'Psychological', 'Power', 'Vulnerability', 'Trapped', 'BDSM'] },
    { id: 18, name: "Exhibitionism", cardType: "Identity/Role", visualHandle: "uncommon_exhibit", primaryElement: "I", elementScores: { A: 6, I: 7, S: 5, P: 7, C: 6, R: 5 }, briefDescription: "Pleasure from being watched.", detailedDescription: "Finding sexual arousal and pleasure in the act of being watched by others during sexual activity, potentially involving performance or revealing oneself.", relatedIds: [19, 12, 34, 50, 78, 90, 91, 105, 33], rarity: 'uncommon', canUnlockArt: false, keywords: ['Exhibitionism', 'Exhibitionist', 'Performance', 'Visual', 'Public', 'Watched', 'Arousal', 'Validation', 'Showing'] },
    { id: 19, name: "Voyeurism", cardType: "Identity/Role", visualHandle: "uncommon_voyeur", primaryElement: "A", elementScores: { A: 7, I: 2, S: 3, P: 6, C: 5, R: 3 }, briefDescription: "Pleasure from watching others.", detailedDescription: "Finding sexual arousal and pleasure primarily from the act of watching others engage in sexual activity, often without their knowledge (consensual voyeurism involves negotiated watching).", relatedIds: [18, 12, 34, 105, 118, 33], rarity: 'uncommon', canUnlockArt: false, keywords: ['Voyeurism', 'Voyeur', 'Observation', 'Visual', 'Arousal', 'Distance', 'Secret', 'Watching', 'Peeping'] },
    { id: 20, name: "Latex/Material Fetish", cardType: "Orientation", visualHandle: "rare_latex", primaryElement: "A", elementScores: { A: 9, I: 5, S: 8, P: 6, C: 5, R: 4 }, briefDescription: "Attraction focused on materials.", detailedDescription: "A specific fetish where sexual arousal is strongly and primarily triggered by the sight, feel, sound, or smell of particular materials like latex, leather, PVC, rubber, silk, etc.", relatedIds: [12, 21, 42, 94], rarity: 'rare', canUnlockArt: true, visualHandleUnlocked: "rare_latex_art", uniquePromptId: "rP20", keywords: ['Fetish', 'Material', 'Latex', 'Leather', 'PVC', 'Rubber', 'Silk', 'Attraction', 'Sensation', 'Focus', 'Clothing', 'Texture'] },
    { id: 21, name: "Uniform/Clothing Fetish", cardType: "Orientation", visualHandle: "rare_uniform", primaryElement: "A", elementScores: { A: 8, I: 6, S: 4, P: 6, C: 6, R: 5 }, briefDescription: "Specific clothing as arousal trigger.", detailedDescription: "A fetish where sexual arousal is significantly and primarily triggered by specific types of clothing, such as uniforms (military, medical, school), costumes, or specific garments (lingerie, suits).", relatedIds: [13, 20, 12, 94, 95, 104], rarity: 'rare', canUnlockArt: false, uniquePromptId: "rP21", keywords: ['Fetish', 'Clothing', 'Uniform', 'Costume', 'Lingerie', 'Attraction', 'Role-Play', 'Visual', 'Outfit'] },
    { id: 22, name: "Monogamy", cardType: "Relationship Style", visualHandle: "common_mono", primaryElement: "R", elementScores: { A: 5, I: 5, S: 5, P: 6, C: 5, R: 2 }, briefDescription: "One partner at a time.", detailedDescription: "The practice or preference for having only one sexual and/or romantic partner at a time, often within a committed, exclusive framework.", relatedIds: [23, 15, 29, 59, 76], rarity: 'common', canUnlockArt: true, visualHandleUnlocked: "common_mono_art", keywords: ['Monogamy', 'Relationship', 'Structure', 'Exclusivity', 'Commitment', 'Couple', 'Dyad', 'One Partner'] },
    { id: 23, name: "Serial Monogamy", cardType: "Relationship Style", visualHandle: "common_serialmono", primaryElement: "R", elementScores: { A: 5, I: 5, S: 5, P: 5, C: 5, R: 3 }, briefDescription: "Sequence of exclusive relationships.", detailedDescription: "The pattern of engaging in sequential monogamous relationships over time, moving from one exclusive partnership to the next.", relatedIds: [22, 24], rarity: 'common', canUnlockArt: false, keywords: ['Monogamy', 'Serial', 'Relationship', 'Structure', 'Exclusivity', 'Sequence', 'Dating'] },
    { id: 24, name: "Casual Sex / Hookups", cardType: "Relationship Style", visualHandle: "common_casual", primaryElement: "R", elementScores: { A: 6, I: 4, S: 6, P: 3, C: 3, R: 5 }, briefDescription: "Sex without commitment.", detailedDescription: "Sexual encounters that occur outside of a committed romantic relationship, typically without expectations of long-term connection or deep emotional intimacy.", relatedIds: [23, 26, 35, 56, 65, 79, 84], rarity: 'common', canUnlockArt: false, keywords: ['Casual Sex', 'Hookup', 'Fleeting', 'Physical', 'Low-Commitment', 'Exploration', 'NSA', 'One Night Stand'] },
    { id: 25, name: "Polyamory", cardType: "Relationship Style", visualHandle: "rare_poly", primaryElement: "R", elementScores: { A: 6, I: 6, S: 5, P: 7, C: 6, R: 8 }, briefDescription: "Multiple loving relationships.", detailedDescription: "The practice of, or desire for, intimate relationships with more than one partner, with the informed consent of all partners involved. Often involves emotional intimacy with multiple people.", relatedIds: [15, 26, 27, 34, 59, 84], rarity: 'rare', canUnlockArt: true, visualHandleUnlocked: "rare_poly_art", uniquePromptId: "rP25", keywords: ['Polyamory', 'Poly', 'Non-Monogamy', 'Multiple Partners', 'Intimacy', 'Connection', 'Structure', 'Loving', 'Ethical'] },
    { id: 26, name: "Open Relationship", cardType: "Relationship Style", visualHandle: "uncommon_openrel", primaryElement: "R", elementScores: { A: 6, I: 5, S: 6, P: 5, C: 5, R: 7 }, briefDescription: "Primary couple + outside sex.", detailedDescription: "A relationship structure, typically involving a primary couple, where partners agree that one or both may have sexual relationships with other people, often with rules about emotional involvement.", relatedIds: [24, 25, 27, 35], rarity: 'uncommon', canUnlockArt: false, keywords: ['Open Relationship', 'Non-Monogamy', 'Structure', 'Rules', 'Openness', 'Couple', 'Primary', 'CNM'] },
    { id: 27, name: "Relationship Anarchy", cardType: "Relationship Style", visualHandle: "rare_ra", primaryElement: "R", elementScores: { A: 6, I: 5, S: 5, P: 6, C: 7, R: 9 }, briefDescription: "Rejects rules/hierarchies.", detailedDescription: "A philosophy and relationship style that rejects societal norms and imposed rules regarding relationships. Each relationship is unique and defined by the individuals involved, without inherent hierarchy.", relatedIds: [25, 26, 36, 59, 84], rarity: 'rare', canUnlockArt: false, uniquePromptId: "rP27", keywords: ['Relationship Anarchy', 'RA', 'Autonomy', 'Fluidity', 'Anti-Hierarchy', 'No Rules', 'Structure', 'Philosophy', 'Non-Monogamy'] },
    { id: 28, name: "Asexuality", cardType: "Orientation", visualHandle: "uncommon_ace", primaryElement: "A", elementScores: { A: 0, I: 3, S: 2, P: 3, C: 3, R: 4 }, briefDescription: "Little or no sexual attraction.", detailedDescription: "Characterized by a persistent lack of sexual attraction towards any gender. Asexual individuals may still experience romantic attraction, desire intimacy, or engage in sexual activity for various reasons.", relatedIds: [29, 36], rarity: 'uncommon', canUnlockArt: false, keywords: ['Asexuality', 'Asexual', 'Ace', 'Orientation', 'Attraction', 'Spectrum', 'Lack'] },
    { id: 29, name: "Demisexuality", cardType: "Orientation", visualHandle: "uncommon_demi", primaryElement: "A", elementScores: { A: 3, I: 4, S: 4, P: 8, C: 5, R: 5 }, briefDescription: "Attraction requires emotional bond.", detailedDescription: "A sexual orientation where an individual only develops sexual attraction after forming a strong emotional connection with someone.", relatedIds: [15, 28, 22, 14], rarity: 'uncommon', canUnlockArt: false, keywords: ['Demisexuality', 'Demisexual', 'Attraction', 'Connection', 'Emotion', 'Intimacy', 'Bond', 'Orientation'] },
    { id: 30, name: "High Protocol D/s", cardType: "Practice/Kink", visualHandle: "rare_protocol", primaryElement: "I", elementScores: { A: 6, I: 8, S: 6, P: 8, C: 9, R: 7 }, briefDescription: "Highly structured power exchange.", detailedDescription: "A style of Dominance and submission characterized by significant structure, formal rules, rituals, specific forms of address, and often pre-negotiated expectations for behavior within the dynamic.", relatedIds: [4, 5, 11, 13, 38, 101, 109], rarity: 'rare', canUnlockArt: true, visualHandleUnlocked: "rare_protocol_art", uniquePromptId: "rP30", keywords: ['Protocol', 'High Protocol', 'Structure', 'Rules', 'Power', 'Cognitive', 'Ritual', 'D/s', 'BDSM', 'Formal'] },
    { id: 31, name: "Cuddling / Affection", cardType: "Practice/Kink", visualHandle: "common_cuddle", primaryElement: "P", elementScores: { A: 3, I: 3, S: 3, P: 6, C: 2, R: 4 }, briefDescription: "Non-sexual physical closeness.", detailedDescription: "Sharing physical closeness through hugging, holding, or lying together without explicit sexual intent, focusing on comfort, security, and platonic or romantic affection.", relatedIds: [2, 15, 48, 69, 80], rarity: 'common', canUnlockArt: false, keywords: ['Cuddle', 'Cuddling', 'Affection', 'Comfort', 'Security', 'Connection', 'Gentle', 'Holding', 'Hugging', 'Platonic'] },
    { id: 32, name: "Dirty Talk", cardType: "Practice/Kink", visualHandle: "common_dirtytalk", primaryElement: "C", elementScores: { A: 5, I: 6, S: 3, P: 5, C: 7, R: 5 }, briefDescription: "Explicit language during sex.", detailedDescription: "Verbally expressing desires, fantasies, commands, or descriptions of acts during sexual activity to increase arousal and connection. Can be suggestive or highly explicit.", relatedIds: [13, 11, 4, 5, 46, 49, 66, 74], rarity: 'common', canUnlockArt: false, keywords: ['Dirty Talk', 'Language', 'Cognitive', 'Arousal', 'Expression', 'Fantasy', 'Words', 'Verbal', 'Explicit'] },
    { id: 33, name: "Mutual Masturbation", cardType: "Practice/Kink", visualHandle: "common_mutualmast", primaryElement: "I", elementScores: { A: 5, I: 5, S: 6, P: 4, C: 4, R: 5 }, briefDescription: "Partners masturbating together.", detailedDescription: "Two or more partners engaging in simultaneous masturbation, potentially watching or manually stimulating each other to orgasm.", relatedIds: [1, 18, 19, 72], rarity: 'common', canUnlockArt: false, keywords: ['Mutual Masturbation', 'Masturbation', 'Shared', 'Physical', 'Visual', 'Sensation', 'Handjob', 'Fingering'] },
    { id: 34, name: "Group Sex", cardType: "Practice/Kink", visualHandle: "uncommon_group", primaryElement: "R", elementScores: { A: 6, I: 6, S: 7, P: 5, C: 4, R: 8 }, briefDescription: "Sex involving 3+ people.", detailedDescription: "Engaging in sexual acts with three or more people simultaneously. Dynamics can vary widely from casual encounters to structured orgies or polyamorous group play.", relatedIds: [18, 19, 25, 26, 27, 35, 65, 105], rarity: 'uncommon', canUnlockArt: false, keywords: ['Group Sex', 'Threesome', 'Foursome', 'Orgy', 'Multiple Partners', 'Interaction', 'Shared Experience', 'Swinging'] },
    { id: 35, name: "Swinging", cardType: "Relationship Style", visualHandle: "uncommon_swing", primaryElement: "R", elementScores: { A: 5, I: 5, S: 6, P: 4, C: 4, R: 7 }, briefDescription: "Couples swapping partners for sex.", detailedDescription: "A lifestyle where committed couples consensually engage in sexual activities with other couples or individuals, often at parties or planned events, typically with an emphasis on recreational sex over deep emotional connection with outside partners.", relatedIds: [26, 24, 34], rarity: 'uncommon', canUnlockArt: false, keywords: ['Swinging', 'Swinger', 'Non-Monogamy', 'Recreation', 'Couple', 'Group', 'Social', 'Partner Swap'] },
    { id: 36, name: "Aromanticism", cardType: "Orientation", visualHandle: "uncommon_aro", primaryElement: "A", elementScores: { A: 2, I: 3, S: 3, P: 4, C: 4, R: 3 }, briefDescription: "Little or no romantic attraction.", detailedDescription: "Characterized by a lack of romantic attraction. Aromantic individuals may still experience sexual attraction (allosexual) or not (aro/ace), and may desire platonic partnerships or other relationship structures.", relatedIds: [28, 27, 59], rarity: 'uncommon', canUnlockArt: false, keywords: ['Aromanticism', 'Aromantic', 'Aro', 'Orientation', 'Romance', 'Spectrum', 'Lack', 'Relationship'] },
    { id: 37, name: "Sensory Deprivation (Light)", cardType: "Practice/Kink", visualHandle: "uncommon_sensdep", primaryElement: "S", elementScores: { A: 4, I: 3, S: 7, P: 6, C: 5, R: 5 }, briefDescription: "Reducing sight/sound (blindfolds).", detailedDescription: "Using blindfolds, hoods, earplugs, or other methods to significantly reduce or eliminate one or more senses, often heightening remaining senses, increasing vulnerability, or creating a specific psychological state. Light deprivation focuses on temporary reduction.", relatedIds: [9, 17, 5, 57, 44, 86, 124], rarity: 'uncommon', canUnlockArt: false, keywords: ['Sensory Deprivation', 'Sense Dep', 'Blindfold', 'Hood', 'Sensation', 'Focus', 'Vulnerability', 'Psychological', 'BDSM'] },
    { id: 38, name: "Teasing & Denial", cardType: "Practice/Kink", visualHandle: "uncommon_denial", primaryElement: "P", elementScores: { A: 6, I: 7, S: 7, P: 8, C: 7, R: 6 }, briefDescription: "Building arousal, withholding orgasm.", detailedDescription: "A form of psychological play and power exchange where one partner intentionally builds the other's arousal close to orgasm but repeatedly denies release, often increasing desperation and reinforcing control dynamics.", relatedIds: [4, 5, 11, 9, 44, 83, 93, 119, 30, 45, 106], rarity: 'uncommon', canUnlockArt: true, visualHandleUnlocked: "uncommon_denial_art", keywords: ['Denial', 'Orgasm Denial', 'Teasing', 'T&D', 'Control', 'Power', 'Psychological', 'Anticipation', 'Edge', 'BDSM'] },
    { id: 39, name: "Age Play", cardType: "Practice/Kink", visualHandle: "uncommon_ageplay", primaryElement: "C", elementScores: { A: 5, I: 6, S: 4, P: 7, C: 8, R: 6 }, briefDescription: "Role-playing different ages.", detailedDescription: "Consensual role-playing where participants adopt personas and behaviors associated with ages different from their own (e.g., caregiver/little, teacher/student). Focus is typically on the dynamic and psychological state, not actual age differences.", relatedIds: [13, 4, 5, 10, 58, 92, 98], rarity: 'uncommon', canUnlockArt: false, keywords: ['Age Play', 'Age Regression', 'Age Progression', 'Role-Play', 'Cognitive', 'Psychological', 'Dynamic', 'CGL', 'DDLG', 'MDLB'] },
    { id: 40, name: "Primal Play", cardType: "Practice/Kink", visualHandle: "uncommon_primal", primaryElement: "I", elementScores: { A: 5, I: 8, S: 7, P: 6, C: 3, R: 5 }, briefDescription: "Instinctive, animalistic interaction.", detailedDescription: "A style of play involving raw, instinctive, and often non-verbal interaction, tapping into animalistic urges like chasing, biting, growling, nuzzling, or struggling. Can range from playful to intense.", relatedIds: [4, 5, 9, 7, 8, 97], rarity: 'uncommon', canUnlockArt: true, visualHandleUnlocked: "uncommon_primal_art", keywords: ['Primal', 'Instinct', 'Interaction', 'Physical', 'Animalistic', 'Non-verbal', 'Bite', 'Growl', 'Chase', 'BDSM'] },
    { id: 41, name: "Erotic Hypnosis / Mind Control Play", cardType: "Practice/Kink", visualHandle: "rare_hypno", primaryElement: "C", elementScores: { A: 5, I: 7, S: 3, P: 8, C: 9, R: 6 }, briefDescription: "Using suggestion/perceived control.", detailedDescription: "Consensual play involving altered states of consciousness, hypnotic suggestion, triggers, or the *illusion* of one partner controlling the other's mind or actions for erotic purposes. Safety and consent are paramount.", relatedIds: [14, 4, 5, 11, 45, 42, 120, 44], rarity: 'rare', canUnlockArt: false, uniquePromptId: "rP41", keywords: ['Hypnosis', 'Erotic Hypnosis', 'Mind Control', 'Cognitive', 'Power', 'Suggestion', 'Altered State', 'Psychological', 'Trance', 'Trigger', 'BDSM'] },
    { id: 42, name: "Transformation Fetish", cardType: "Orientation", visualHandle: "rare_transform", primaryElement: "C", elementScores: { A: 7, I: 4, S: 5, P: 7, C: 8, R: 4 }, briefDescription: "Arousal from transformation themes.", detailedDescription: "A fetish centered on the concept of transformation, which can include physical changes (e.g., into animals, objects, different genders), mental changes (e.g., bimbofication, personality alteration), or forced changes within a power dynamic.", relatedIds: [20, 21, 12, 41, 14, 121], rarity: 'rare', canUnlockArt: false, uniquePromptId: "rP42", keywords: ['Transformation', 'TF', 'Fetish', 'Cognitive', 'Fantasy', 'Change', 'Identity', 'Animal', 'Object', 'Gender', 'Bimbo'] },
    { id: 43, name: "Medical Play", cardType: "Practice/Kink", visualHandle: "rare_medical", primaryElement: "C", elementScores: { A: 5, I: 6, S: 7, P: 7, C: 7, R: 6 }, briefDescription: "Role-playing medical scenarios.", detailedDescription: "Consensual role-playing involving medical themes, settings, or equipment. Can range from simple doctor/patient scenarios to more clinical interactions involving mock examinations, implements (speculums, needles - potentially real/blunt), restraints, or power dynamics inherent in medical settings.", relatedIds: [13, 9, 17, 4, 5], rarity: 'rare', canUnlockArt: false, uniquePromptId: "rP43", keywords: ['Medical Play', 'Med Fetish', 'Role-Play', 'Scenario', 'Power', 'Clinical', 'Sensation', 'Doctor', 'Nurse', 'Patient', 'Examination', 'Needle', 'BDSM'] },
    { id: 44, name: "Edge Play", cardType: "Practice/Kink", visualHandle: "rare_edge", primaryElement: "S", elementScores: { A: 5, I: 6, S: 9, P: 8, C: 5, R: 6 }, briefDescription: "Pushing boundaries near limits.", detailedDescription: "Activities that intentionally push physical, psychological, or emotional boundaries close to perceived limits. Often involves negotiation, high trust, and managing real or perceived risk (e.g., breath play, knife play, extreme sensation, fear play). Requires significant caution, expertise, and communication.", relatedIds: [8, 9, 16, 17, 37, 38, 41, 63, 64, 65, 106, 111, 113, 116, 122, 125], rarity: 'rare', canUnlockArt: false, uniquePromptId: "rP44", keywords: ['Edge Play', 'Risk', 'Intensity', 'Sensation', 'Psychological', 'Trust', 'Boundary', 'Limit', 'Danger', 'Fear', 'BDSM'] },
    { id: 45, name: "Humiliation / Degradation", cardType: "Psychological/Goal", visualHandle: "rare_humiliation", primaryElement: "P", elementScores: { A: 5, I: 7, S: 4, P: 9, C: 6, R: 6 }, briefDescription: "Pleasure from embarrassment/degradation.", detailedDescription: "Consensual play where one partner derives pleasure from performing or receiving acts or words intended to cause embarrassment, shame, or degradation. Can range from light teasing to intense psychological scenarios. Consent and aftercare are critical.", relatedIds: [4, 5, 10, 11, 12, 38, 41, 99, 100, 114, 115, 120], rarity: 'rare', canUnlockArt: false, uniquePromptId: "rP45", keywords: ['Humiliation', 'Degradation', 'Psychological', 'Power', 'Emotion', 'Shame', 'Taboo', 'Embarrassment', 'Erotic Humiliation', 'BDSM'] },
    { id: 46, name: "Compliments / Praise", cardType: "Practice/Kink", visualHandle: "common_praise", primaryElement: "P", elementScores: { A: 4, I: 5, S: 2, P: 7, C: 4, R: 5 }, briefDescription: "Verbal affirmation during intimacy.", detailedDescription: "Using positive verbal feedback, compliments, or praise related to appearance, performance, or desirability to enhance connection, confidence, and arousal.", relatedIds: [32, 15, 50], rarity: 'common', canUnlockArt: false, keywords: ['Praise', 'Compliments', 'Validation', 'Affirmation', 'Psychological', 'Connection', 'Confidence', 'Verbal', 'Words'] },
    { id: 47, name: "Eye Contact", cardType: "Practice/Kink", visualHandle: "common_eyecontact", primaryElement: "P", elementScores: { A: 5, I: 6, S: 2, P: 7, C: 3, R: 6 }, briefDescription: "Intense gazing during intimacy.", detailedDescription: "Maintaining direct and often intense eye contact during sexual activity to heighten intimacy, connection, vulnerability, or sometimes power dynamics.", relatedIds: [3, 15], rarity: 'common', canUnlockArt: false, keywords: ['Eye Contact', 'Gazing', 'Intimacy', 'Connection', 'Vulnerability', 'Presence', 'Focus', 'Soul Gazing'] },
    { id: 48, name: "Holding Hands", cardType: "Practice/Kink", visualHandle: "common_handholding", primaryElement: "P", elementScores: { A: 3, I: 4, S: 3, P: 5, C: 1, R: 4 }, briefDescription: "Simple physical connection.", detailedDescription: "The simple act of clasping hands, often signifying affection, connection, comfort, or partnership, whether during sexual activity or not.", relatedIds: [2, 31, 77], rarity: 'common', canUnlockArt: false, keywords: ['Holding Hands', 'Handholding', 'Affection', 'Connection', 'Comfort', 'Simple', 'Touch', 'Partnership'] },
    { id: 49, name: "Shared Fantasy Talk", cardType: "Practice/Kink", visualHandle: "common_fantasytalk", primaryElement: "C", elementScores: { A: 5, I: 5, S: 3, P: 6, C: 6, R: 5 }, briefDescription: "Verbally sharing fantasies.", detailedDescription: "Partners verbally describing their sexual fantasies to each other, either as a form of mutual arousal or to build towards potential future play.", relatedIds: [32, 14], rarity: 'common', canUnlockArt: false, keywords: ['Fantasy', 'Talk', 'Cognitive', 'Sharing', 'Arousal', 'Communication', 'Verbal', 'Imagination'] },
    { id: 50, name: "Validation Seeking", cardType: "Psychological/Goal", visualHandle: "common_validation", primaryElement: "P", elementScores: { A: 5, I: 6, S: 5, P: 7, C: 4, R: 5 }, briefDescription: "Sex motivated by feeling desired.", detailedDescription: "Engaging in sexual activity partly or primarily motivated by the need to feel desired, attractive, skilled, or validated by a partner's reactions or praise.", relatedIds: [18, 46, 91], rarity: 'common', canUnlockArt: false, keywords: ['Validation', 'Psychological', 'Need', 'Desire', 'Performance', 'Approval', 'Esteem', 'Attractive'] },
    { id: 51, name: "Stress Relief Focus", cardType: "Psychological/Goal", visualHandle: "common_stressrelief", primaryElement: "P", elementScores: { A: 4, I: 4, S: 5, P: 6, C: 3, R: 4 }, briefDescription: "Using sex to unwind/relax.", detailedDescription: "Utilizing sexual activity, including orgasm, primarily as a means to release tension, reduce stress, and achieve a state of relaxation.", relatedIds: [1], rarity: 'common', canUnlockArt: false, keywords: ['Stress Relief', 'Relaxation', 'Physical', 'Catharsis', 'Unwind', 'Release', 'Coping'] },
    { id: 52, name: "Heterosexuality", cardType: "Orientation", visualHandle: "common_hetero", primaryElement: "A", elementScores: { A: 7, I: 5, S: 5, P: 5, C: 5, R: 5 }, briefDescription: "Attraction to different gender(s).", detailedDescription: "Sexual and/or romantic attraction primarily to individuals of a different gender identity than one's own.", relatedIds: [53, 54, 55], rarity: 'common', canUnlockArt: false, keywords: ['Heterosexual', 'Straight', 'Orientation', 'Gender', 'Attraction', 'Different Sex'] },
    { id: 53, name: "Homosexuality", cardType: "Orientation", visualHandle: "common_homo", primaryElement: "A", elementScores: { A: 7, I: 5, S: 5, P: 5, C: 5, R: 5 }, briefDescription: "Attraction to same gender(s).", detailedDescription: "Sexual and/or romantic attraction primarily to individuals of the same gender identity as one's own.", relatedIds: [52, 54, 55], rarity: 'common', canUnlockArt: false, keywords: ['Homosexual', 'Gay', 'Lesbian', 'Orientation', 'Gender', 'Attraction', 'Same Sex'] },
    { id: 54, name: "Bisexuality", cardType: "Orientation", visualHandle: "common_bi", primaryElement: "A", elementScores: { A: 6, I: 5, S: 5, P: 5, C: 5, R: 5 }, briefDescription: "Attraction to two or more genders.", detailedDescription: "Sexual and/or romantic attraction to more than one gender identity, potentially including one's own and different genders.", relatedIds: [52, 53, 55], rarity: 'common', canUnlockArt: false, keywords: ['Bisexual', 'Bi', 'Orientation', 'Gender', 'Attraction', 'Multiple', 'More Than One'] },
    { id: 55, name: "Pansexuality", cardType: "Orientation", visualHandle: "common_pan", primaryElement: "A", elementScores: { A: 5, I: 5, S: 5, P: 5, C: 5, R: 5 }, briefDescription: "Attraction regardless of gender.", detailedDescription: "Sexual and/or romantic attraction to individuals regardless of their gender identity or presentation. Attraction may be focused on other qualities.", relatedIds: [52, 53, 54, 103], rarity: 'common', canUnlockArt: false, keywords: ['Pansexual', 'Pan', 'Orientation', 'Attraction', 'Fluidity', 'Personality', 'Regardless of Gender'] },
    { id: 56, name: "Quickie", cardType: "Practice/Kink", visualHandle: "common_quickie", primaryElement: "I", elementScores: { A: 6, I: 6, S: 6, P: 3, C: 2, R: 4 }, briefDescription: "Brief, often spontaneous sex.", detailedDescription: "A short sexual encounter, often focused on achieving orgasm quickly due to time constraints or a desire for immediate gratification.", relatedIds: [1, 24, 79], rarity: 'common', canUnlockArt: false, keywords: ['Quickie', 'Brief', 'Spontaneous', 'Physical', 'Goal-Oriented', 'Fast', 'Short'] },
    { id: 57, name: "Sensory Enhancement", cardType: "Practice/Kink", visualHandle: "uncommon_sensenh", primaryElement: "S", elementScores: { A: 4, I: 5, S: 7, P: 5, C: 4, R: 5}, briefDescription: "Heightening specific senses.", detailedDescription: "Using techniques or tools (like feathers, ice, vibration, specific sounds/scents) specifically to amplify or focus on particular sensory inputs, often after a period of deprivation or contrast.", relatedIds: [2, 37, 7, 9, 86, 88, 102, 112], rarity: 'uncommon', canUnlockArt: false, keywords: ['Sensation', 'Sensory', 'Focus', 'Enhancement', 'Physical', 'Tools', 'Feather', 'Ice', 'Vibration', 'Sound', 'Smell'] },
    { id: 58, name: "Caregiver/Little Dynamics", cardType: "Psychological/Goal", visualHandle: "uncommon_cgl", primaryElement: "P", elementScores: { A: 5, I: 7, S: 4, P: 8, C: 6, R: 7 }, briefDescription: "Nurturing/dependent role-play.", detailedDescription: "A dynamic, often linked with Age Play, involving one partner taking on a nurturing, authoritative Caregiver role (DD/lg, MD/lb, etc.) and the other adopting a more dependent, vulnerable Little role.", relatedIds: [39, 4, 5, 10, 15, 82], rarity: 'uncommon', canUnlockArt: false, keywords: ['Caregiver', 'Little', 'CGL', 'DDLG', 'MDLB', 'Nurturing', 'Dependence', 'Role-Play', 'Psychological', 'Vulnerability', 'Age Play'] },
    { id: 59, name: "Platonic Partnership / QPR", cardType: "Relationship Style", visualHandle: "uncommon_qpr", primaryElement: "R", elementScores: { A: 3, I: 4, S: 3, P: 7, C: 5, R: 6 }, briefDescription: "Deep non-romantic commitment.", detailedDescription: "Queerplatonic Relationships (QPRs) or other committed platonic partnerships involve a deep bond, commitment, and intimacy that transcends typical friendship norms but is not inherently romantic or sexual.", relatedIds: [22, 36, 15, 27, 25], rarity: 'uncommon', canUnlockArt: false, keywords: ['Platonic', 'Partnership', 'QPR', 'Queerplatonic', 'Commitment', 'Intimacy', 'Relationship', 'Non-Romantic', 'Aromantic'] },
    { id: 60, name: "Sapiosexuality", cardType: "Orientation", visualHandle: "uncommon_sapio", primaryElement: "A", elementScores: { A: 7, I: 5, S: 3, P: 6, C: 8, R: 5 }, briefDescription: "Attraction to intelligence.", detailedDescription: "Finding intelligence to be the most sexually attractive feature in a person, potentially outweighing physical appearance or other factors.", relatedIds: [49, 74, 81], rarity: 'uncommon', canUnlockArt: false, keywords: ['Sapiosexual', 'Attraction', 'Intelligence', 'Cognitive', 'Mind', 'Intellect', 'Orientation'] },
    { id: 61, name: "Body Worship", cardType: "Practice/Kink", visualHandle: "uncommon_bodyworship", primaryElement: "P", elementScores: { A: 6, I: 4, S: 6, P: 8, C: 3, R: 6 }, briefDescription: "Reverential focus on partner's body.", detailedDescription: "Expressing adoration or reverence for a partner's body through acts like kissing, licking, massaging, or simply admiring specific parts, often within a power exchange dynamic.", relatedIds: [5, 10, 12, 62, 102], rarity: 'uncommon', canUnlockArt: false, keywords: ['Worship', 'Body Worship', 'Devotion', 'Adoration', 'Psychological', 'Focus', 'Body', 'Reverence', 'Submissive'] },
    { id: 62, name: "Foot Fetish / Podophilia", cardType: "Orientation", visualHandle: "uncommon_footfetish", primaryElement: "A", elementScores: { A: 8, I: 4, S: 7, P: 5, C: 3, R: 4 }, briefDescription: "Sexual interest focused on feet.", detailedDescription: "A specific paraphilia involving sexual arousal derived from feet. This can include kissing, licking, massaging, or incorporating feet into other sexual acts.", relatedIds: [61, 12, 102], rarity: 'uncommon', canUnlockArt: false, keywords: ['Fetish', 'Feet', 'Foot', 'Podophilia', 'Attraction', 'Focus', 'Sensation', 'Paraphilia'] },
    { id: 63, name: "Breath Play", cardType: "Practice/Kink", visualHandle: "rare_breath", primaryElement: "S", elementScores: { A: 4, I: 7, S: 9, P: 8, C: 4, R: 6 }, briefDescription: "Restricting airflow for sensation.", detailedDescription: "Consensual practice involving the restriction of airflow (erotic asphyxiation) to create intense physical sensations and altered mental states. Carries significant risks and requires extreme caution, knowledge, and trust.", relatedIds: [44, 17, 9, 5, 125], rarity: 'rare', canUnlockArt: false, uniquePromptId: "rP63", keywords: ['Breath Play', 'Asphyxiation', 'Erotic Asphyxiation', 'Risk', 'Edge Play', 'Sensation', 'Altered State', 'Trust', 'Choking', 'BDSM'] },
    { id: 64, name: "CNC (Consensual Non-Consent)", cardType: "Practice/Kink", visualHandle: "rare_cnc", primaryElement: "C", elementScores: { A: 6, I: 7, S: 7, P: 8, C: 9, R: 6 }, briefDescription: "Role-playing lack of consent.", detailedDescription: "Consensual role-playing scenarios where participants act out a scene involving simulated non-consent or coercion (e.g., simulated rape fantasy, abduction). Requires meticulous negotiation, clear boundaries, safewords, and trust.", relatedIds: [13, 4, 5, 17, 44, 117, 118], rarity: 'rare', canUnlockArt: false, uniquePromptId: "rP64", keywords: ['CNC', 'Consensual Non-Consent', 'Role-Play', 'Fantasy', 'Cognitive', 'Power', 'Taboo', 'Consent', 'Rape Fantasy', 'Force', 'BDSM'] },
    { id: 65, name: "Chemsex / Party & Play (PnP)", cardType: "Practice/Kink", visualHandle: "rare_chemsex", primaryElement: "S", elementScores: { A: 6, I: 6, S: 8, P: 7, C: 3, R: 7 }, briefDescription: "Using drugs to enhance sex.", detailedDescription: "Intentionally combining sexual activity with the use of psychoactive drugs (like methamphetamine, GHB, mephedrone) to sustain activity, reduce inhibitions, or intensify sensations. Carries health risks and potential for addiction.", relatedIds: [34, 24, 44], rarity: 'rare', canUnlockArt: false, uniquePromptId: "rP65", keywords: ['Chemsex', 'PnP', 'Party and Play', 'Drugs', 'Substance Use', 'Sensation', 'Endurance', 'Risk', 'Social', 'Meth', 'GHB'] },
    { id: 66, name: "Foreplay Focus", cardType: "Practice/Kink", visualHandle: "common_foreplay", primaryElement: "I", elementScores: { A: 5, I: 6, S: 5, P: 5, C: 4, R: 5 }, briefDescription: "Emphasis on pre-intercourse intimacy.", detailedDescription: "Placing significant importance on activities leading up to intercourse or the main sexual event, such as kissing, touching, oral sex, or dirty talk, to build arousal and connection.", relatedIds: [1, 2, 3, 32, 67, 83], rarity: 'common', canUnlockArt: false, keywords: ['Foreplay', 'Build-up', 'Arousal', 'Connection', 'Intimacy', 'Anticipation', 'Kissing', 'Touching', 'Oral Sex'] },
    { id: 67, name: "Oral Sex (Giving/Receiving)", cardType: "Practice/Kink", visualHandle: "common_oral", primaryElement: "S", elementScores: { A: 6, I: 6, S: 7, P: 5, C: 3, R: 5 }, briefDescription: "Stimulation with mouth/tongue.", detailedDescription: "Engaging in oral stimulation of a partner's genitals (fellatio, cunnilingus) or other erogenous zones.", relatedIds: [1, 66, 73, 107], rarity: 'common', canUnlockArt: false, keywords: ['Oral Sex', 'Fellatio', 'Cunnilingus', 'Blowjob', 'Licking', 'Sensation', 'Physical', 'Focus', 'Giving', 'Receiving', 'Mouth'] },
    { id: 68, name: "Romantic Gestures", cardType: "Psychological/Goal", visualHandle: "common_romantic", primaryElement: "P", elementScores: { A: 5, I: 5, S: 3, P: 7, C: 4, R: 6 }, briefDescription: "Expressing love/care non-sexually.", detailedDescription: "Actions taken to express love, affection, or care that are not explicitly sexual but enhance the relationship context, such as gift-giving, date nights, or thoughtful acts.", relatedIds: [15, 22, 31, 76], rarity: 'common', canUnlockArt: false, keywords: ['Romance', 'Romantic', 'Affection', 'Care', 'Relationship', 'Connection', 'Gesture', 'Love', 'Gift'] },
    { id: 69, name: "Aftercare (Basic)", cardType: "Practice/Kink", visualHandle: "common_aftercare", primaryElement: "P", elementScores: { A: 4, I: 5, S: 4, P: 6, C: 3, R: 6 }, briefDescription: "Post-sex connection/comfort.", detailedDescription: "Providing comfort, reassurance, and connection immediately following sexual activity, such as cuddling, talking, providing water, or checking in emotionally.", relatedIds: [31, 15, 70, 80, 123], rarity: 'common', canUnlockArt: false, keywords: ['Aftercare', 'Comfort', 'Connection', 'Care', 'Post-Scene', 'Psychological', 'Reassurance', 'Cuddling', 'BDSM'] },
    { id: 70, name: "Pillow Talk", cardType: "Practice/Kink", visualHandle: "common_pillowtalk", primaryElement: "P", elementScores: { A: 4, I: 4, S: 2, P: 7, C: 4, R: 7 }, briefDescription: "Intimate conversation after sex.", detailedDescription: "Engaging in relaxed, intimate, and often vulnerable conversation with a partner after sexual activity.", relatedIds: [69, 15], rarity: 'common', canUnlockArt: false, keywords: ['Pillow Talk', 'Intimacy', 'Conversation', 'Vulnerability', 'Connection', 'Post-Scene', 'Sharing', 'Talking'] },
    { id: 71, name: "Shower/Bath Sex", cardType: "Practice/Kink", visualHandle: "common_showersex", primaryElement: "S", elementScores: { A: 5, I: 5, S: 6, P: 4, C: 3, R: 5 }, briefDescription: "Sexual activity in water.", detailedDescription: "Engaging in sexual acts in a shower or bath, often incorporating the sensations of water and steam.", relatedIds: [1], rarity: 'common', canUnlockArt: false, keywords: ['Shower Sex', 'Bath Sex', 'Sensation', 'Environment', 'Water', 'Playful', 'Wet'] },
    { id: 72, name: "Using Sex Toys (Simple)", cardType: "Practice/Kink", visualHandle: "common_toys_simple", primaryElement: "S", elementScores: { A: 5, I: 5, S: 6, P: 4, C: 3, R: 4 }, briefDescription: "Incorporating basic vibrators/dildos.", detailedDescription: "Using common sex toys like simple vibrators or dildos for added stimulation during solo or partnered play.", relatedIds: [1, 33, 73], rarity: 'common', canUnlockArt: false, keywords: ['Sex Toys', 'Toys', 'Vibrator', 'Dildo', 'Sensation', 'Stimulation', 'Physical', 'Solo', 'Partnered'] },
    { id: 73, name: "Lubricant Use", cardType: "Practice/Kink", visualHandle: "common_lube", primaryElement: "S", elementScores: { A: 4, I: 4, S: 5, P: 3, C: 2, R: 4 }, briefDescription: "Enhancing comfort/sensation.", detailedDescription: "Using personal lubricants to increase comfort, reduce friction, or enhance sensation during various sexual activities.", relatedIds: [1, 67, 72], rarity: 'common', canUnlockArt: false, keywords: ['Lubricant', 'Lube', 'Comfort', 'Sensation', 'Physical', 'Practical', 'Friction'] },
    { id: 74, name: "Flirting / Banter", cardType: "Interaction", visualHandle: "common_flirt", primaryElement: "I", elementScores: { A: 6, I: 7, S: 3, P: 5, C: 6, R: 5 }, briefDescription: "Playful, suggestive communication.", detailedDescription: "Engaging in lighthearted, often witty or suggestive conversation aimed at building attraction and rapport.", relatedIds: [32, 60, 75], rarity: 'common', canUnlockArt: false, keywords: ['Flirting', 'Banter', 'Playful', 'Communication', 'Cognitive', 'Attraction', 'Rapport', 'Suggestive', 'Witty'] },
    { id: 75, name: "Shared Humor", cardType: "Psychological/Goal", visualHandle: "common_humor", primaryElement: "P", elementScores: { A: 5, I: 6, S: 2, P: 6, C: 5, R: 6 }, briefDescription: "Finding connection through laughter.", detailedDescription: "Valuing and enjoying shared laughter and humor within intimate interactions as a way to build connection and ease tension.", relatedIds: [74, 15], rarity: 'common', canUnlockArt: false, keywords: ['Humor', 'Laughter', 'Connection', 'Playful', 'Psychological', 'Lightness', 'Shared'] },
    { id: 76, name: "Date Nights", cardType: "Relationship Style", visualHandle: "common_datenight", primaryElement: "R", elementScores: { A: 4, I: 5, S: 4, P: 6, C: 4, R: 5 }, briefDescription: "Dedicated time for connection.", detailedDescription: "Setting aside specific time for shared activities aimed at fostering connection and intimacy within a relationship, which may or may not lead to sex.", relatedIds: [68, 15, 22], rarity: 'common', canUnlockArt: false, keywords: ['Date Night', 'Relationship', 'Connection', 'Ritual', 'Intimacy', 'Quality Time', 'Couple'] },
    { id: 77, name: "Public Display Affection (Mild)", cardType: "Practice/Kink", visualHandle: "common_pda", primaryElement: "R", elementScores: { A: 4, I: 5, S: 3, P: 5, C: 2, R: 5 }, briefDescription: "Holding hands, brief kisses in public.", detailedDescription: "Showing affection to a partner in public spaces through generally acceptable gestures like holding hands, brief kisses, or an arm around the shoulder.", relatedIds: [48, 3, 78], rarity: 'common', canUnlockArt: false, keywords: ['PDA', 'Public Display Affection', 'Public', 'Affection', 'Subtle', 'Relationship', 'Holding Hands', 'Kiss'] },
    { id: 78, name: "Public Display Affection (Moderate)", cardType: "Practice/Kink", visualHandle: "uncommon_pda_mod", primaryElement: "R", elementScores: { A: 5, I: 6, S: 4, P: 6, C: 3, R: 6 }, briefDescription: "Making out, groping in semi-public.", detailedDescription: "Engaging in more overt displays of affection or arousal in public or semi-public spaces, potentially pushing social boundaries.", relatedIds: [77, 18], rarity: 'uncommon', canUnlockArt: false, keywords: ['PDA', 'Public Display Affection', 'Public', 'Exhibitionism', 'Risk', 'Thrill', 'Affection', 'Making Out', 'Groping'] },
    { id: 79, name: "Spontaneity Seeker", cardType: "Psychological/Goal", visualHandle: "common_spontaneity", primaryElement: "P", elementScores: { A: 6, I: 6, S: 6, P: 5, C: 3, R: 5 }, briefDescription: "Enjoying unplanned encounters.", detailedDescription: "Deriving particular enjoyment from unexpected or spontaneous sexual encounters or expressions of desire.", relatedIds: [56, 24], rarity: 'common', canUnlockArt: false, keywords: ['Spontaneity', 'Spontaneous', 'Excitement', 'Unpredictable', 'Physical', 'Impulsive'] },
    { id: 80, name: "Comfort Seeker", cardType: "Psychological/Goal", visualHandle: "common_comfort", primaryElement: "P", elementScores: { A: 3, I: 3, S: 4, P: 7, C: 2, R: 4 }, briefDescription: "Using intimacy for security/soothing.", detailedDescription: "Primarily seeking physical closeness and intimacy (not necessarily orgasm) for feelings of safety, security, and emotional soothing.", relatedIds: [31, 2, 69], rarity: 'common', canUnlockArt: false, keywords: ['Comfort', 'Security', 'Psychological', 'Affection', 'Soothing', 'Safety', 'Closeness'] },
    { id: 81, name: "Attraction to Confidence", cardType: "Orientation", visualHandle: "common_attr_conf", primaryElement: "A", elementScores: { A: 7, I: 6, S: 4, P: 6, C: 5, R: 5 }, briefDescription: "Finding self-assuredness attractive.", detailedDescription: "Being primarily attracted to individuals who exhibit strong self-confidence, assertiveness, or a commanding presence.", relatedIds: [4, 60], rarity: 'common', canUnlockArt: false, keywords: ['Attraction', 'Confidence', 'Power', 'Personality', 'Assertiveness', 'Self-assured'] },
    { id: 82, name: "Attraction to Kindness", cardType: "Orientation", visualHandle: "common_attr_kind", primaryElement: "A", elementScores: { A: 5, I: 4, S: 4, P: 7, C: 4, R: 6 }, briefDescription: "Finding compassion/empathy attractive.", detailedDescription: "Being primarily attracted to individuals who exhibit kindness, empathy, compassion, and nurturing qualities.", relatedIds: [15, 58], rarity: 'common', canUnlockArt: false, keywords: ['Attraction', 'Kindness', 'Empathy', 'Connection', 'Personality', 'Compassion', 'Nurturing'] },
    { id: 83, name: "Slow Burn", cardType: "Practice/Kink", visualHandle: "common_slowburn", primaryElement: "P", elementScores: { A: 5, I: 5, S: 5, P: 7, C: 5, R: 6 }, briefDescription: "Gradual build-up of intimacy/arousal.", detailedDescription: "Preferring a gradual, extended build-up of emotional intimacy and sexual tension over time or within an encounter, rather than immediate gratification.", relatedIds: [15, 66, 38], rarity: 'common', canUnlockArt: false, keywords: ['Slow Burn', 'Anticipation', 'Intimacy', 'Tension', 'Psychological', 'Pacing', 'Gradual', 'Build-up'] },
    { id: 84, name: "Solo Polyamory", cardType: "Relationship Style", visualHandle: "uncommon_solopoly", primaryElement: "R", elementScores: { A: 5, I: 5, S: 5, P: 6, C: 6, R: 7 }, briefDescription: "Multiple partners, maintains independence.", detailedDescription: "Practicing polyamory while choosing to live independently and prioritize personal autonomy, not necessarily seeking primary-style partnerships or cohabitation.", relatedIds: [25, 27, 24], rarity: 'uncommon', canUnlockArt: false, keywords: ['Solo Polyamory', 'Solo Poly', 'Polyamory', 'Non-Monogamy', 'Autonomy', 'Independence', 'Structure', 'Relationship'] },
    { id: 85, name: "Make-up Sex", cardType: "Psychological/Goal", visualHandle: "common_makeupsex", primaryElement: "P", elementScores: { A: 6, I: 6, S: 6, P: 7, C: 3, R: 5 }, briefDescription: "Sex after conflict resolution.", detailedDescription: "Engaging in sexual activity following an argument or conflict, often characterized by heightened emotions and a sense of reconciliation.", relatedIds: [3], rarity: 'common', canUnlockArt: false, keywords: ['Make-up Sex', 'Emotion', 'Intensity', 'Reconciliation', 'Catharsis', 'Argument', 'Conflict'] },
    { id: 86, name: "Sensory Overload", cardType: "Practice/Kink", visualHandle: "uncommon_sens_overload", primaryElement: "S", elementScores: { A: 5, I: 6, S: 8, P: 6, C: 4, R: 5 }, briefDescription: "Intentionally overwhelming senses.", detailedDescription: "Simultaneously applying multiple strong sensory inputs (touch, sound, sight, etc.) to overwhelm the senses, potentially leading to altered states or intense reactions.", relatedIds: [37, 57, 8, 124], rarity: 'uncommon', canUnlockArt: false, keywords: ['Sensory Overload', 'Intensity', 'Sensation', 'Altered State', 'Psychological', 'Overwhelm', 'Stimulation', 'BDSM'] },
    { id: 87, name: "Light Bondage (Cuffs/Silk)", cardType: "Practice/Kink", visualHandle: "uncommon_bond_light", primaryElement: "S", elementScores: { A: 5, I: 5, S: 6, P: 6, C: 4, R: 5 }, briefDescription: "Using simple restraints.", detailedDescription: "Using simple restraints like handcuffs, fuzzy cuffs, or silk scarves for playful restriction or temporary immobilization, emphasizing sensation and light power exchange.", relatedIds: [16, 17, 5, 93], rarity: 'uncommon', canUnlockArt: false, keywords: ['Bondage', 'Light Bondage', 'Restraint', 'Cuffs', 'Silk', 'Restriction', 'Playful', 'Sensation', 'Power', 'BDSM'] },
    { id: 88, name: "Temperature Play (Wax/Ice)", cardType: "Practice/Kink", visualHandle: "uncommon_temp_play", primaryElement: "S", elementScores: { A: 5, I: 6, S: 7, P: 6, C: 3, R: 5 }, briefDescription: "Using heat/cold for sensation.", detailedDescription: "Using safe temperature variations, like low-temperature wax or ice cubes, on the skin to create contrasting and intense sensations.", relatedIds: [9, 57], rarity: 'uncommon', canUnlockArt: true, visualHandleUnlocked: "uncommon_temp_play_art", keywords: ['Temperature Play', 'Temp Play', 'Wax Play', 'Ice Play', 'Sensation', 'Contrast', 'Physical', 'Pain Play', 'Heat', 'Cold', 'BDSM'] },
    { id: 89, name: "Power Play (Subtle)", cardType: "Psychological/Goal", visualHandle: "uncommon_power_subtle", primaryElement: "P", elementScores: { A: 6, I: 7, S: 5, P: 7, C: 7, R: 6 }, briefDescription: "Enjoying implicit power dynamics.", detailedDescription: "Finding arousal or satisfaction in the subtle negotiation and expression of power within an interaction, without necessarily adopting explicit D/s roles or commands.", relatedIds: [4, 5, 11, 90], rarity: 'uncommon', canUnlockArt: false, keywords: ['Power Play', 'Power Dynamics', 'Subtle', 'Implicit', 'Psychological', 'Dynamic', 'Negotiation', 'Cognitive', 'Control'] },
    { id: 90, name: "Performance Focus (Top)", cardType: "Identity/Role", visualHandle: "uncommon_perf_top", primaryElement: "I", elementScores: { A: 5, I: 8, S: 6, P: 7, C: 6, R: 5 }, briefDescription: "Enjoying orchestrating partner's pleasure.", detailedDescription: "A dominant or topping style focused on skillfully providing pleasure and controlling the sensory experience for the partner, often enjoying the partner's reactions as validation.", relatedIds: [4, 11, 18, 89], rarity: 'uncommon', canUnlockArt: false, keywords: ['Performance', 'Top', 'Dominant', 'Control', 'Pleasure', 'Skill', 'Validation', 'Leading', 'Orchestrate'] },
    { id: 91, name: "Performance Focus (Bottom)", cardType: "Identity/Role", visualHandle: "uncommon_perf_bot", primaryElement: "I", elementScores: { A: 5, I: 3, S: 6, P: 7, C: 5, R: 5 }, briefDescription: "Enjoying reacting/expressing pleasure.", detailedDescription: "A submissive or bottoming style focused on expressing reactions and pleasure authentically and visibly, finding satisfaction in showing their response to the partner's actions.", relatedIds: [5, 18, 50], rarity: 'uncommon', canUnlockArt: false, keywords: ['Performance', 'Bottom', 'Submissive', 'Reaction', 'Expression', 'Pleasure', 'Validation', 'Following', 'Showing'] },
    { id: 92, name: "Gender Play", cardType: "Practice/Kink", visualHandle: "uncommon_genderplay", primaryElement: "C", elementScores: { A: 6, I: 6, S: 4, P: 6, C: 7, R: 5 }, briefDescription: "Exploring/subverting gender roles.", detailedDescription: "Consensually playing with or subverting traditional gender roles, expressions, or presentations within a sexual context (e.g., cross-dressing, adopting gender-nonconforming personas).", relatedIds: [13, 39, 103], rarity: 'uncommon', canUnlockArt: false, keywords: ['Gender Play', 'Genderfuck', 'Cross-dressing', 'Gender Expression', 'Role-Play', 'Cognitive', 'Expression', 'Fluidity', 'Subversion'] },
    { id: 93, name: "Tickling (Erotic)", cardType: "Practice/Kink", visualHandle: "uncommon_tickle", primaryElement: "S", elementScores: { A: 4, I: 6, S: 6, P: 5, C: 3, R: 5 }, briefDescription: "Using tickling for arousal/play.", detailedDescription: "Using tickling as a form of playful torture, teasing, or sensory stimulation within an erotic context, often combined with light restraint.", relatedIds: [7, 38, 87], rarity: 'uncommon', canUnlockArt: false, keywords: ['Tickling', 'Erotic Tickling', 'Playful', 'Sensation', 'Control', 'Teasing', 'Torture', 'BDSM'] },
    { id: 94, name: "Leather Fetish", cardType: "Orientation", visualHandle: "uncommon_leather", primaryElement: "A", elementScores: { A: 8, I: 6, S: 7, P: 6, C: 5, R: 5 }, briefDescription: "Attraction focused on leather.", detailedDescription: "Specific arousal triggered by the sight, smell, sound, or feel of leather garments or items, often associated with BDSM or specific subcultures.", relatedIds: [20, 21, 4], rarity: 'uncommon', canUnlockArt: false, keywords: ['Fetish', 'Leather', 'Material', 'Attraction', 'Sensation', 'Subculture', 'Clothing', 'BDSM'] },
    { id: 95, name: "Lingerie Focus", cardType: "Orientation", visualHandle: "uncommon_lingerie", primaryElement: "A", elementScores: { A: 7, I: 5, S: 5, P: 5, C: 4, R: 4 }, briefDescription: "Arousal enhanced by specific underwear.", detailedDescription: "Finding specific types of lingerie or underwear particularly arousing, either on oneself or a partner.", relatedIds: [21], rarity: 'uncommon', canUnlockArt: false, keywords: ['Lingerie', 'Underwear', 'Attraction', 'Visual', 'Clothing', 'Fabric', 'Fetish'] },
    { id: 96, name: "Hair Pulling", cardType: "Practice/Kink", visualHandle: "uncommon_hairpull", primaryElement: "S", elementScores: { A: 5, I: 7, S: 6, P: 5, C: 2, R: 5 }, briefDescription: "Using hair pulling for control/sensation.", detailedDescription: "Incorporating pulling a partner's hair during sexual activity for sensation, control, or to guide movement.", relatedIds: [7, 9, 4], rarity: 'uncommon', canUnlockArt: false, keywords: ['Hair Pulling', 'Hairpull', 'Sensation', 'Control', 'Physical', 'Dominance', 'Rough'] },
    { id: 97, name: "Biting / Marking", cardType: "Practice/Kink", visualHandle: "uncommon_biting", primaryElement: "S", elementScores: { A: 5, I: 7, S: 7, P: 6, C: 3, R: 5 }, briefDescription: "Using teeth for sensation/possession.", detailedDescription: "Incorporating biting (from gentle nips to harder bites that may leave marks) for intense sensation, primal expression, or as a sign of possession.", relatedIds: [9, 8, 40], rarity: 'uncommon', canUnlockArt: false, keywords: ['Biting', 'Marking', 'Sensation', 'Primal', 'Possession', 'Intensity', 'Teeth', 'Love Bite', 'Hickey'] },
    { id: 98, name: "Pet Play", cardType: "Practice/Kink", visualHandle: "uncommon_petplay", primaryElement: "C", elementScores: { A: 5, I: 6, S: 5, P: 7, C: 7, R: 6 }, briefDescription: "Role-playing as animals/pets.", detailedDescription: "Consensual role-play where one or more participants adopt the persona and behaviors of an animal or pet (e.g., kitten, puppy), often involving specific gear, dynamics, and interactions.", relatedIds: [13, 39, 4, 5, 10, 121], rarity: 'uncommon', canUnlockArt: false, keywords: ['Pet Play', 'Role-Play', 'Cognitive', 'Psychological', 'Animalistic', 'Dynamic', 'Kitten', 'Puppy', 'Human Pet', 'BDSM'] },
    { id: 99, name: "Masochism (Psychological)", cardType: "Psychological/Goal", visualHandle: "uncommon_maso_psych", primaryElement: "P", elementScores: { A: 5, I: 3, S: 4, P: 8, C: 6, R: 5 }, briefDescription: "Pleasure from emotional submission/distress.", detailedDescription: "Deriving pleasure or release from experiencing consensually inflicted emotional distress, humiliation, powerlessness, or psychological challenge.", relatedIds: [5, 17, 45, 100, 120], rarity: 'uncommon', canUnlockArt: false, keywords: ['Masochism', 'Psychological Masochism', 'Emotion', 'Submission', 'Distress', 'Catharsis', 'Humiliation', 'Powerlessness', 'Challenge', 'BDSM'] },
    { id: 100, name: "Sadism (Psychological)", cardType: "Psychological/Goal", visualHandle: "uncommon_sad_psych", primaryElement: "P", elementScores: { A: 5, I: 7, S: 4, P: 8, C: 7, R: 5 }, briefDescription: "Pleasure from causing emotional distress.", detailedDescription: "Deriving pleasure or satisfaction from consensually inflicting emotional distress, humiliation, or psychological challenge upon a partner.", relatedIds: [4, 11, 45, 99, 120], rarity: 'uncommon', canUnlockArt: false, keywords: ['Sadism', 'Psychological Sadism', 'Emotion', 'Control', 'Distress', 'Humiliation', 'Challenge', 'Power', 'BDSM'] },
    { id: 101, name: "Ritualistic Play", cardType: "Practice/Kink", visualHandle: "uncommon_ritual", primaryElement: "C", elementScores: { A: 6, I: 7, S: 6, P: 7, C: 8, R: 7 }, briefDescription: "Using ceremony/symbolism in scenes.", detailedDescription: "Incorporating elements of ritual, ceremony, symbolism, or formalized structure into sexual scenes or BDSM dynamics to enhance meaning, power exchange, or psychological impact.", relatedIds: [30, 11, 13, 16, 116], rarity: 'uncommon', canUnlockArt: true, visualHandleUnlocked: "uncommon_ritual_art", keywords: ['Ritual', 'Ritualistic', 'Cognitive', 'Structure', 'Symbolism', 'Meaning', 'Power', 'Ceremony', 'Scene', 'BDSM'] },
    { id: 102, name: "Sensory Focus (Specific Zone)", cardType: "Practice/Kink", visualHandle: "uncommon_sens_zone", primaryElement: "S", elementScores: { A: 5, I: 6, S: 7, P: 5, C: 4, R: 5 }, briefDescription: "Intense focus on one body part.", detailedDescription: "Concentrating intense sensory stimulation (touch, temperature, vibration, etc.) on a specific erogenous zone or body part for an extended period.", relatedIds: [57, 2, 61, 62], rarity: 'uncommon', canUnlockArt: false, keywords: ['Sensation', 'Sensory Focus', 'Body Part', 'Intensity', 'Physical', 'Erogenous Zone', 'Stimulation'] },
    { id: 103, name: "Androgyny Attraction", cardType: "Orientation", visualHandle: "uncommon_andro", primaryElement: "A", elementScores: { A: 7, I: 5, S: 5, P: 5, C: 5, R: 5 }, briefDescription: "Attraction to androgynous presentation.", detailedDescription: "Sexual or aesthetic attraction primarily towards individuals whose gender presentation is androgynous, blending traditionally masculine and feminine characteristics.", relatedIds: [55, 92], rarity: 'uncommon', canUnlockArt: false, keywords: ['Androgyny', 'Attraction', 'Gender Presentation', 'Aesthetic', 'Orientation', 'Non-binary'] },
    { id: 104, name: "Power Attire", cardType: "Orientation", visualHandle: "uncommon_powerattire", primaryElement: "A", elementScores: { A: 7, I: 6, S: 4, P: 6, C: 5, R: 5 }, briefDescription: "Arousal from authoritative clothing.", detailedDescription: "Finding clothing associated with power, authority, or formality (e.g., business suits, uniforms, formal wear) particularly arousing.", relatedIds: [21, 4], rarity: 'uncommon', canUnlockArt: false, keywords: ['Power Attire', 'Attraction', 'Clothing', 'Power', 'Authority', 'Uniform', 'Suit', 'Formal', 'Fetish'] },
    { id: 105, name: "Voyeuristic Exhibitionism", cardType: "Identity/Role", visualHandle: "uncommon_voy_exhib", primaryElement: "I", elementScores: { A: 7, I: 7, S: 5, P: 7, C: 6, R: 6 }, briefDescription: "Pleasure from mutual watching/being watched.", detailedDescription: "A dynamic where arousal comes from both watching others and being watched, often in group settings or where partners take turns performing and observing.", relatedIds: [18, 19, 34], rarity: 'uncommon', canUnlockArt: false, keywords: ['Exhibitionism', 'Voyeurism', 'Visual', 'Performance', 'Shared', 'Watching', 'Group'] },
    { id: 106, name: "Fear Play (Mild)", cardType: "Practice/Kink", visualHandle: "uncommon_fear_mild", primaryElement: "P", elementScores: { A: 5, I: 6, S: 6, P: 7, C: 5, R: 5 }, briefDescription: "Using startle/anticipation.", detailedDescription: "Incorporating elements of surprise, startle responses, or anticipation of intense sensation/actions to generate adrenaline and psychological tension within a safe context.", relatedIds: [44, 38, 9, 111, 122], rarity: 'uncommon', canUnlockArt: false, keywords: ['Fear Play', 'Fear', 'Anticipation', 'Thrill', 'Psychological', 'Edge', 'Startle', 'Surprise', 'Adrenaline', 'BDSM'] },
    { id: 107, name: "Tribadism / Scissoring", cardType: "Practice/Kink", visualHandle: "uncommon_tribadism", primaryElement: "S", elementScores: { A: 5, I: 6, S: 7, P: 5, C: 2, R: 5 }, briefDescription: "Vulva-to-vulva rubbing.", detailedDescription: "A sexual practice involving rubbing vulvas together for mutual stimulation and friction.", relatedIds: [1, 67], rarity: 'uncommon', canUnlockArt: false, keywords: ['Tribadism', 'Scissoring', 'Physical', 'Sensation', 'Friction', 'Vulva', 'Lesbian', 'Queer'] },
    { id: 108, name: "Intercrural Sex (Frotting)", cardType: "Practice/Kink", visualHandle: "uncommon_frotting", primaryElement: "S", elementScores: { A: 5, I: 6, S: 7, P: 5, C: 2, R: 5 }, briefDescription: "Penis-to-penis rubbing.", detailedDescription: "A sexual practice involving rubbing penises together for mutual stimulation and friction.", relatedIds: [1], rarity: 'uncommon', canUnlockArt: false, keywords: ['Frotting', 'Frot', 'Intercrural', 'Physical', 'Sensation', 'Friction', 'Penis', 'Gay', 'Queer'] },
    { id: 109, name: "Master/slave Dynamic (M/s)", cardType: "Relationship Style", visualHandle: "rare_ms", primaryElement: "I", elementScores: { A: 6, I: 9, S: 6, P: 9, C: 8, R: 7 }, briefDescription: "Total power exchange relationship.", detailedDescription: "A specific, high-intensity form of D/s relationship involving a deep level of commitment and power exchange, often encompassing many aspects of life beyond the bedroom. Uses specific titles.", relatedIds: [4, 5, 11, 30, 10], rarity: 'rare', canUnlockArt: false, uniquePromptId: "rP109", keywords: ['M/s', 'Master', 'Slave', 'Power Exchange', 'TPE', 'Commitment', 'Structure', 'D/s', 'Lifestyle', 'BDSM', 'Relationship'] },
    { id: 110, name: "Figging", cardType: "Practice/Kink", visualHandle: "uncommon_figging", primaryElement: "S", elementScores: { A: 3, I: 6, S: 8, P: 6, C: 3, R: 5 }, briefDescription: "Using ginger root for intense sensation.", detailedDescription: "Inserting a piece of peeled ginger root into the anus or vagina, causing an intense burning sensation. An older BDSM practice requiring caution.", relatedIds: [9, 8], rarity: 'uncommon', canUnlockArt: false, keywords: ['Figging', 'Ginger', 'Sensation', 'Intensity', 'Pain Play', 'BDSM', 'Burning', 'Punishment'] },
    { id: 111, name: "Knife Play / Edge Play (Sharp)", cardType: "Practice/Kink", visualHandle: "rare_knife", primaryElement: "S", elementScores: { A: 5, I: 7, S: 9, P: 8, C: 6, R: 6 }, briefDescription: "Using blades for sensation/fear.", detailedDescription: "Edge play involving the use of knives or other sharp objects against the skin for sensation, psychological fear, or light marking (drawing blood is extremely risky and requires advanced knowledge). Intense focus on control and trust.", relatedIds: [44, 9, 106, 4, 116], rarity: 'rare', canUnlockArt: false, uniquePromptId: "rP111", keywords: ['Knife Play', 'Edge Play', 'Risk', 'Fear', 'Sensation', 'Control', 'Trust', 'Blade', 'Sharp', 'BDSM'] },
    { id: 112, name: "Electrostimulation (E-Stim)", cardType: "Practice/Kink", visualHandle: "rare_estim", primaryElement: "S", elementScores: { A: 4, I: 6, S: 9, P: 6, C: 4, R: 5 }, briefDescription: "Using electrical currents for sensation.", detailedDescription: "Using specialized devices (like TENS units adapted or purpose-built) to pass mild electrical currents through the body for unique tingling, buzzing, or contracting sensations.", relatedIds: [9, 57, 119], rarity: 'rare', canUnlockArt: true, visualHandleUnlocked: "rare_estim_art", uniquePromptId: "rP112", keywords: ['E-Stim', 'Electrostimulation', 'Electro', 'Sensation', 'Intensity', 'Involuntary', 'Technology', 'TENS', 'Violet Wand', 'BDSM'] },
    { id: 113, name: "Suspension Bondage", cardType: "Practice/Kink", visualHandle: "rare_suspension", primaryElement: "S", elementScores: { A: 5, I: 7, S: 9, P: 8, C: 6, R: 6 }, briefDescription: "Lifting partner off ground with rope/chains.", detailedDescription: "A form of bondage where a person is partially or fully suspended off the ground using ropes, chains, or other equipment. Requires significant technical skill, knowledge of rigging, and safety precautions.", relatedIds: [16, 17, 44], rarity: 'rare', canUnlockArt: false, uniquePromptId: "rP113", keywords: ['Suspension', 'Bondage', 'Rope', 'Risk', 'Skill', 'Helplessness', 'Intensity', 'Air', 'Hanging', 'BDSM'] },
    { id: 114, name: "Water Sports / Urolagnia", cardType: "Practice/Kink", visualHandle: "rare_watersports", primaryElement: "S", elementScores: { A: 6, I: 6, S: 7, P: 7, C: 4, R: 5 }, briefDescription: "Incorporating urine into play.", detailedDescription: "Sexual arousal or activity involving urine (also known as golden showers). Can range from watching urination to being urinated on or drinking urine. Consent and hygiene are important.", relatedIds: [45, 12, 115], rarity: 'rare', canUnlockArt: false, uniquePromptId: "rP114", keywords: ['Watersports', 'Urolagnia', 'Urine', 'Piss Play', 'Golden Shower', 'Taboo', 'Humiliation', 'Bodily Fluids', 'Wet', 'BDSM'] },
    { id: 115, name: "Scat Play / Coprophilia", cardType: "Practice/Kink", visualHandle: "rare_scat", primaryElement: "S", elementScores: { A: 5, I: 5, S: 6, P: 8, C: 3, R: 4 }, briefDescription: "Incorporating feces into play.", detailedDescription: "Sexual arousal or activity involving feces. Considered an extreme fetish with significant health risks and stigma. Requires extreme caution regarding hygiene and consent.", relatedIds: [114, 45], rarity: 'rare', canUnlockArt: false, uniquePromptId: "rP115", keywords: ['Scat', 'Coprophilia', 'Feces', 'Poop Play', 'Taboo', 'Extreme', 'Risk', 'Bodily Fluids', 'Dirty', 'BDSM'] },
    { id: 116, name: "Blood Play (Intentional)", cardType: "Practice/Kink", visualHandle: "rare_bloodplay", primaryElement: "S", elementScores: { A: 5, I: 7, S: 8, P: 8, C: 5, R: 6 }, briefDescription: "Consensual use of blood in scenes.", detailedDescription: "Consensually incorporating small amounts of blood (drawn safely, e.g., via lancet) into sexual or ritualistic scenes. Carries significant health risks (bloodborne pathogens) and requires stringent safety protocols.", relatedIds: [44, 111, 101], rarity: 'rare', canUnlockArt: false, uniquePromptId: "rP116", keywords: ['Blood Play', 'Blood', 'Risk', 'Edge Play', 'Ritual', 'Intensity', 'Taboo', 'Cutting', 'Sacrifice', 'BDSM'] },
    { id: 117, name: "Abduction / Capture Fantasy", cardType: "Practice/Kink", visualHandle: "rare_abduction", primaryElement: "C", elementScores: { A: 6, I: 7, S: 7, P: 8, C: 9, R: 6 }, briefDescription: "Role-playing non-consensual capture.", detailedDescription: "A specific type of CNC role-play focusing on the scenario of being abducted, captured, or held against one's will within a pre-negotiated, safe container.", relatedIds: [64, 13, 17, 44, 122], rarity: 'rare', canUnlockArt: false, uniquePromptId: "rP117", keywords: ['Abduction', 'Capture', 'CNC', 'Role-Play', 'Fantasy', 'Fear', 'Power', 'Struggle', 'Taken', 'BDSM'] },
    { id: 118, name: "Somnophilia / Sleep Play", cardType: "Practice/Kink", visualHandle: "rare_somno", primaryElement: "C", elementScores: { A: 7, I: 3, S: 6, P: 7, C: 7, R: 4 }, briefDescription: "Arousal related to sleeping individuals.", detailedDescription: "Sexual arousal derived from interacting with or observing someone who is asleep or feigning sleep. Often involves themes of vulnerability and voyeurism. Consent when awake is paramount for ethical play.", relatedIds: [19, 17, 64], rarity: 'rare', canUnlockArt: false, uniquePromptId: "rP118", keywords: ['Somnophilia', 'Sleep Play', 'Sleeping', 'Vulnerability', 'Voyeurism', 'Consent', 'Fantasy', 'Unaware'] },
    { id: 119, name: "Forced Orgasm / Orgasm Control", cardType: "Practice/Kink", visualHandle: "rare_forceorgasm", primaryElement: "I", elementScores: { A: 5, I: 8, S: 8, P: 8, C: 7, R: 6 }, briefDescription: "Controlling partner's orgasm.", detailedDescription: "A power dynamic where one partner controls if, when, and how the other partner experiences orgasm, potentially pushing them past limits or denying it completely.", relatedIds: [38, 11, 4, 5, 112], rarity: 'rare', canUnlockArt: false, uniquePromptId: "rP119", keywords: ['Orgasm Control', 'Forced Orgasm', 'Power', 'Control', 'Denial', 'Pleasure', 'Intensity', 'Release', 'BDSM'] },
    { id: 120, name: "Psychological Torture Play", cardType: "Practice/Kink", visualHandle: "rare_psychtorture", primaryElement: "P", elementScores: { A: 4, I: 7, S: 4, P: 9, C: 8, R: 6 }, briefDescription: "Intense mind games/emotional manipulation.", detailedDescription: "Consensual play involving intense psychological manipulation, mind games, gaslighting (within agreed limits), or emotional challenges designed to push mental boundaries. Requires extreme trust and aftercare.", relatedIds: [45, 41, 100, 99, 11], rarity: 'rare', canUnlockArt: false, uniquePromptId: "rP120", keywords: ['Psychological Torture', 'Mind Games', 'Mindfuck', 'Manipulation', 'Emotion', 'Power', 'Edge Play', 'Trust', 'Gaslighting', 'BDSM'] },
    { id: 121, name: "Furry Fandom Sexuality", cardType: "Identity/Role", visualHandle: "rare_furrysex", primaryElement: "C", elementScores: { A: 6, I: 6, S: 5, P: 6, C: 7, R: 6 }, briefDescription: "Sexual expression within furry context.", detailedDescription: "Expressing sexuality through or within the context of the furry fandom, which may involve anthropomorphic characters (fursonas), costumes (fursuits), role-play, and specific community norms.", relatedIds: [13, 98, 42], rarity: 'rare', canUnlockArt: false, uniquePromptId: "rP121", keywords: ['Furry', 'Fandom', 'Identity', 'Role-Play', 'Community', 'Anthropomorphic', 'Fursona', 'Fursuit', 'Yiff'] },
    { id: 122, name: "Autassassinophilia", cardType: "Orientation", visualHandle: "rare_autassass", primaryElement: "P", elementScores: { A: 5, I: 2, S: 7, P: 8, C: 6, R: 3 }, briefDescription: "Arousal from staged risk of being killed.", detailedDescription: "A paraphilia involving sexual arousal from the fantasy or staged scenario of being hunted or stalked with the risk of being killed.", relatedIds: [44, 106, 117], rarity: 'rare', canUnlockArt: false, uniquePromptId: "rP122", keywords: ['Autassassinophilia', 'Risk', 'Fear', 'Edge Play', 'Fantasy', 'Thrill', 'Danger', 'Death', 'Stalking', 'Paraphilia'] },
    { id: 123, name: "Exposure Therapy Play", cardType: "Psychological/Goal", visualHandle: "rare_exposure", primaryElement: "P", elementScores: { A: 4, I: 6, S: 5, P: 8, C: 7, R: 7 }, briefDescription: "Using scenes to process trauma/fear.", detailedDescription: "Carefully negotiated and consensual scenes designed to gently re-approach or process past trauma or fears within a supportive BDSM context. Requires immense trust and often therapeutic awareness.", relatedIds: [15, 69, 4, 5], rarity: 'rare', canUnlockArt: false, uniquePromptId: "rP123", keywords: ['Exposure Therapy', 'Trauma', 'Healing', 'Psychological', 'Trust', 'Safety', 'BDSM', 'Processing', 'Fear', 'Therapeutic'] },
    { id: 124, name: "Sensory Overstimulation Torture", cardType: "Practice/Kink", visualHandle: "rare_sens_torture", primaryElement: "S", elementScores: { A: 4, I: 7, S: 9, P: 7, C: 5, R: 6 }, briefDescription: "Using prolonged/intense stimuli.", detailedDescription: "Intentionally using prolonged, inescapable, or intensely unpleasant sensory input (e.g., specific sounds, lights, textures, smells) as a form of consensual 'torture' play.", relatedIds: [86, 37, 9, 44], rarity: 'rare', canUnlockArt: false, uniquePromptId: "rP124", keywords: ['Sensory Overload', 'Torture', 'Intensity', 'Sensation', 'Endurance', 'Control', 'Overstimulation', 'Unpleasant', 'BDSM'] },
    { id: 125, name: "Breath Control (Advanced)", cardType: "Practice/Kink", visualHandle: "rare_breath_adv", primaryElement: "S", elementScores: { A: 4, I: 7, S: 9, P: 8, C: 4, R: 6 }, briefDescription: "Precise manipulation of breathing.", detailedDescription: "Advanced forms of breath play involving more precise control over inhalation/exhalation, potentially using bags or masks under highly controlled and knowledgeable conditions. Extremely high risk.", relatedIds: [63, 44, 17], rarity: 'rare', canUnlockArt: false, uniquePromptId: "rP125", keywords: ['Breath Play', 'Breath Control', 'Asphyxiation', 'Risk', 'Edge Play', 'Control', 'Intensity', 'Skill', 'Advanced', 'Bag', 'Mask', 'BDSM'] },
];

// --- Utility Maps & Arrays ---
const elementKeyToFullName = { A: "Attraction", I: "Interaction", S: "Sensory", P: "Psychological", C: "Cognitive", R: "Relational" };
const elementNameToKey = Object.fromEntries(Object.entries(elementKeyToFullName).map(([key, value]) => [value, key]));
const cardTypeKeys = ["Orientation", "Identity/Role", "Practice/Kink", "Psychological/Goal", "Relationship Style", "Cognitive"]; // Added Cognitive just in case
const elementNames = ["Attraction", "Interaction", "Sensory", "Psychological", "Cognitive", "Relational"];

// --- Questionnaire Data (Keep as is) ---
const questionnaireGuided = {
    "Attraction": [ { qId: "a1", type: "slider", text: "How specific are the triggers for your sexual attraction? (e.g., Very broad vs. Very specific types/situations)", minValue: 0, maxValue: 10, defaultValue: 5, minLabel: "Very Broad / Few Specifics", maxLabel: "Very Specific / Narrow Focus", scoreWeight: 1.0 }, { qId: "a2", type: "checkbox", text: "Which factors significantly contribute to your initial attraction? (Select up to 2)", options: [ { value: "Physical Appearance/Body Type", points: 0.5 }, { value: "Gender Identity/Presentation", points: 0.5 }, { value: "Personality/Demeanor", points: 0.0 }, { value: "Intellect/Wit", points: 0.5 }, { value: "Signs of Power/Confidence", points: 1.0 }, { value: "Signs of Vulnerability/Submissiveness", points: 1.0 }, { value: "Emotional Connection (Pre-existing)", points: -1.0 }, { value: "Specific Clothing/Materials", points: 1.5 }, { value: "Context/Situation (e.g., role-play)", points: 1.0 } ], scoreWeight: 1.0, maxChoices: 2 }, { qId: "a3", type: "radio", text: "How important is an emotional bond BEFORE feeling sexual attraction?", options: [ { value: "Essential", points: -2.0 }, { value: "Helpful, but not required", points: -0.5 }, { value: "Neutral / Varies", points: 0 }, { value: "Generally unimportant", points: 1.0 } ], scoreWeight: 1.0 } ],
    "Interaction": [ { qId: "i1", type: "slider", text: "In sexual interactions, where do you naturally find yourself on the spectrum of leading vs. following?", minValue: 0, maxValue: 10, defaultValue: 5, minLabel: "Strongly Following / Receiving", maxLabel: "Strongly Leading / Directing", scoreWeight: 1.0 }, { qId: "i2", type: "checkbox", text: "Which interaction styles or roles feel most appealing? (Select up to 2)", options: [ { value: "Taking Charge / Dominating", points: 1.5 }, { value: "Guiding / Being Attentive (Top/Caregiver)", points: 1.0 }, { value: "Collaborating / Switching Roles", points: 0 }, { value: "Following Directions / Submitting", points: -1.5 }, { value: "Serving / Pleasing Partner", points: -1.0 }, { value: "Performing / Being Watched", points: 0.5 }, { value: "Playful / Teasing", points: 0.0 } ], scoreWeight: 1.0, maxChoices: 2 }, { qId: "i3", type: "radio", text: "Do you prefer clear power dynamics or more equal footing?", options: [ { value: "Clear Power Difference (D/s)", points: 1.5 }, { value: "Subtle Power Dynamics", points: 0.5 }, { value: "Equal Footing / Collaborative", points: -1.0 }, { value: "Varies Greatly / No Preference", points: 0 } ], scoreWeight: 1.0 } ],
    "Sensory": [ { qId: "s1", type: "slider", text: "How important is the intensity and variety of physical sensation to your arousal?", minValue: 0, maxValue: 10, defaultValue: 5, minLabel: "Low Importance / Subtle Preferred", maxLabel: "High Importance / Intensity Craved", scoreWeight: 1.0 }, { qId: "s2", type: "checkbox", text: "Which types of physical sensations are particularly appealing? (Select up to 2)", options: [ { value: "Gentle Touch / Caressing / Warmth", points: -1.0 }, { value: "Firm Pressure / Massage / Hugging", points: 0.0 }, { value: "Sharp / Stinging (Spanking, Biting)", points: 1.5 }, { value: "Burning / Temperature Play (Wax, Ice)", points: 1.5 }, { value: "Restriction / Binding / Helplessness", points: 1.0 }, { value: "Specific Textures (Latex, Silk, Rope)", points: 1.0 }, { value: "Vibration / Electrostimulation", points: 1.5 } ], scoreWeight: 1.0, maxChoices: 2 }, { qId: "s3", type: "radio", text: "How do you feel about incorporating pain or extreme sensations?", options: [ { value: "Strongly Drawn To It", points: 2.0 }, { value: "Open To Exploring It", points: 1.0 }, { value: "Neutral / Indifferent", points: 0 }, { value: "Prefer to Avoid It", points: -1.0 }, { value: "Strongly Averse To It", points: -2.0 } ], scoreWeight: 1.0 } ],
    "Psychological": [ { qId: "p1", type: "slider", text: "How much is your sexuality tied to fulfilling deeper emotional or psychological needs (beyond physical pleasure)?", minValue: 0, maxValue: 10, defaultValue: 5, minLabel: "Very Little / Primarily Physical", maxLabel: "Very Much / Primary Driver", scoreWeight: 1.0 }, { qId: "p2", type: "checkbox", text: "Which psychological needs does sex MOST effectively help you meet? (Select up to 2)", options: [ { value: "Deep Connection / Intimacy / Trust", points: 1.5 }, { value: "Power / Control (Giving or Receiving)", points: 1.5 }, { value: "Validation / Feeling Desired", points: 1.0 }, { value: "Escape / Stress Relief / Forgetting", points: 0.5 }, { value: "Catharsis / Emotional Release", points: 1.0 }, { value: "Self-Exploration / Identity Expression", points: 0.5 }, { value: "Security / Comfort / Nurturing", points: 0.0 }, { value: "Simple Fun / Recreation", points: -1.0 } ], scoreWeight: 1.0, maxChoices: 2 }, { qId: "p3", type: "radio", text: "Does sex feel incomplete if a specific psychological need isn't addressed?", options: [ { value: "Yes, Often", points: 1.5 }, { value: "Sometimes", points: 0.5 }, { value: "Rarely", points: -0.5 }, { value: "Never", points: -1.5 } ], scoreWeight: 1.0 } ],
    "Cognitive": [ { qId: "c1", type: "slider", text: "How important is mental engagement (fantasy, scenarios, intellect) during sex?", minValue: 0, maxValue: 10, defaultValue: 5, minLabel: "Not Important / Prefer Presence", maxLabel: "Very Important / Mentally Driven", scoreWeight: 1.0 }, { qId: "c2", type: "checkbox", text: "Which mental aspects significantly enhance your arousal? (Select up to 2)", options: [ { value: "Detailed Internal Fantasies", points: 1.5 }, { value: "Specific Role-Playing Scenarios", points: 1.5 }, { value: "Dirty Talk / Erotic Language", points: 1.0 }, { value: "Intellectual Banter / Mind Games", points: 1.0 }, { value: "Understanding Partner's Psychology", points: 0.5 }, { value: "Anticipation / Pre-Planned Scenes", points: 1.0 }, { value: "Being Fully 'In the Moment'", points: -1.5 } ], scoreWeight: 1.0, maxChoices: 2 }, { qId: "c3", type: "radio", text: "Do you prefer spontaneous encounters or more planned/scripted ones?", options: [ { value: "Strongly Prefer Planned/Scripted", points: 1.5 }, { value: "Lean Towards Planned", points: 0.5 }, { value: "No Real Preference / Mix", points: 0 }, { value: "Lean Towards Spontaneous", points: -0.5 }, { value: "Strongly Prefer Spontaneous", points: -1.5 } ], scoreWeight: 1.0 } ],
    "Relational": [ { qId: "r1", type: "slider", text: "What is your ideal relationship structure regarding number of partners?", minValue: 0, maxValue: 10, defaultValue: 3, minLabel: "Strictly One (Monogamy) / Solitary", maxLabel: "Multiple Partners / Fluidity", scoreWeight: 1.0 }, { qId: "r2", type: "checkbox", text: "Which relationship contexts feel most comfortable or desirable? (Select up to 2)", options: [ { value: "Solitary / Self-Exploration", points: -1.5 }, { value: "Deeply Committed Monogamous Pair", points: -1.0 }, { value: "Casual Dating / Friends With Benefits", points: 0.5 }, { value: "Open Relationship (Primary + Others)", points: 1.0 }, { value: "Polyamory (Multiple Equal Relationships)", points: 1.5 }, { value: "Group Sex Scenarios", points: 1.0 }, { value: "Anonymous Encounters", points: 0.5 } ], scoreWeight: 1.0, maxChoices: 2 }, { qId: "r3", type: "radio", text: "How important is relationship 'hierarchy' (e.g., having a 'primary' partner)?", options: [ { value: "Very Important / Need a Primary", points: -1.0 }, { value: "Somewhat Important / Prefer Hierarchy", points: -0.5 }, { value: "Neutral / Depends on Relationship", points: 0 }, { value: "Prefer Non-Hierarchical", points: 1.0 }, { value: "Strongly Against Hierarchy (Anarchy)", points: 1.5 } ], scoreWeight: 1.0 } ]
};

// --- Reflection Prompts (Keep as is) ---
const reflectionPrompts = { /* ... Keep existing reflectionPrompts content ... */ };

// --- Element Deep Dive Content (Keep as is) ---
const elementDeepDive = { /* ... Keep existing elementDeepDive content ... */ };

// --- Focus Rituals Data (Keep as is) ---
const focusRituals = [ /* ... Keep existing focusRituals content ... */ ];

// --- Repository Item Data (Keep as is) ---
const sceneBlueprints = [ /* ... Keep existing sceneBlueprints content ... */ ];
const alchemicalExperiments = [ /* ... Keep existing alchemicalExperiments content ... */ ];
const elementalInsights = [ /* ... Keep existing elementalInsights content ... */ ];

// --- Focus-Driven Unlocks Data (Keep as is) ---
const focusDrivenUnlocks = [ /* ... Keep existing focusDrivenUnlocks content ... */ ];

// --- Rituals & Milestones Data (Keep as is) ---
const dailyRituals = [ /* ... Keep existing dailyRituals content ... */ ];
const milestones = [ /* ... Keep existing milestones content ... */ ];

// --- Tapestry Narrative Generation Data (Keep as is) ---
const elementInteractionThemes = { /* ... Keep existing elementInteractionThemes content ... */ };
const cardTypeThemes = { /* ... Keep existing cardTypeThemes content ... */ };

// *** EXPORTS (MUST BE AT THE VERY END) ***
export {
    elementDetails,
    concepts,
    questionnaireGuided,
    reflectionPrompts,
    elementDeepDive,
    focusRituals,
    sceneBlueprints,
    alchemicalExperiments,
    elementalInsights,
    focusDrivenUnlocks,
    dailyRituals,
    milestones,
    elementKeyToFullName,
    elementNameToKey,
    cardTypeKeys,
    elementNames,
    elementInteractionThemes,
    cardTypeThemes
};

console.log("data.js exports defined.");
console.log("data.js finished.");
