// data.js - COMPLETE VERSION v9 (Insight, Focus Slots, Dissonance, More Concepts, Questionnaire Included)

// --- Core Element Details ---
const elementDetails = { /* ... Same as previous version ... */ };

// --- Concepts Data (Expanded to ~60) ---
const concepts = [
    // --- Common Concepts --- (~20)
    { id: 1, name: "Vanilla Sex", cardType: "Practice/Kink", visualHandle: "common_vanilla", primaryElement: "S", elementScores: { A: 5, I: 5, S: 3, P: 4, C: 3, R: 4 }, briefDescription: "Conventional sexual activity.", detailedDescription: "Refers to sexual expression generally considered within conventional norms, often focused on penile-vaginal intercourse or mutual masturbation without specific power dynamics, intense sensations, or elaborate scenarios.", relatedIds: [2, 3, 33], rarity: 'common', canUnlockArt: false },
    { id: 2, name: "Sensual Touch", cardType: "Practice/Kink", visualHandle: "common_sensual", primaryElement: "S", elementScores: { A: 4, I: 4, S: 4, P: 5, C: 2, R: 4 }, briefDescription: "Gentle, affectionate touch.", detailedDescription: "Focus on gentle, affectionate, and pleasurable touch, emphasizing connection, warmth, and non-goal-oriented physical intimacy. Can include massage, caressing, holding.", relatedIds: [1, 15, 31, 3], rarity: 'common', canUnlockArt: true, visualHandleUnlocked: "common_sensual_art" },
    { id: 3, name: "Passionate Kissing", cardType: "Practice/Kink", visualHandle: "common_kissing", primaryElement: "S", elementScores: { A: 6, I: 5, S: 5, P: 6, C: 3, R: 5 }, briefDescription: "Intense, emotional kissing.", detailedDescription: "Intense and emotionally charged kissing as a primary form of connection and arousal. Can range from deep and lingering to urgent and demanding.", relatedIds: [1, 2, 15], rarity: 'common', canUnlockArt: false },
    { id: 22, name: "Monogamy", cardType: "Relationship Style", visualHandle: "common_mono", primaryElement: "R", elementScores: { A: 5, I: 5, S: 5, P: 6, C: 5, R: 2 }, briefDescription: "One partner at a time.", detailedDescription: "The practice or preference for having only one sexual and/or romantic partner at a time, often within a committed, exclusive framework.", relatedIds: [23, 15, 29], rarity: 'common', canUnlockArt: true, visualHandleUnlocked: "common_mono_art" },
    { id: 23, name: "Serial Monogamy", cardType: "Relationship Style", visualHandle: "common_serialmono", primaryElement: "R", elementScores: { A: 5, I: 5, S: 5, P: 5, C: 5, R: 3 }, briefDescription: "Sequence of exclusive relationships.", detailedDescription: "The pattern of engaging in sequential monogamous relationships over time, moving from one exclusive partnership to the next.", relatedIds: [22, 24], rarity: 'common', canUnlockArt: false },
    { id: 24, name: "Casual Sex / Hookups", cardType: "Relationship Style", visualHandle: "common_casual", primaryElement: "R", elementScores: { A: 6, I: 4, S: 6, P: 3, C: 3, R: 5 }, briefDescription: "Sex without commitment.", detailedDescription: "Sexual encounters that occur outside of a committed romantic relationship, typically without expectations of long-term connection or deep emotional intimacy.", relatedIds: [23, 26, 35], rarity: 'common', canUnlockArt: false },
    { id: 31, name: "Cuddling / Affection", cardType: "Practice/Kink", visualHandle: "common_cuddle", primaryElement: "P", elementScores: { A: 3, I: 3, S: 3, P: 6, C: 2, R: 4 }, briefDescription: "Non-sexual physical closeness.", detailedDescription: "Sharing physical closeness through hugging, holding, or lying together without explicit sexual intent, focusing on comfort, security, and platonic or romantic affection.", relatedIds: [2, 15], rarity: 'common', canUnlockArt: false },
    { id: 32, name: "Dirty Talk", cardType: "Practice/Kink", visualHandle: "common_dirtytalk", primaryElement: "C", elementScores: { A: 5, I: 6, S: 3, P: 5, C: 7, R: 5 }, briefDescription: "Explicit language during sex.", detailedDescription: "Verbally expressing desires, fantasies, commands, or descriptions of acts during sexual activity to increase arousal and connection. Can be suggestive or highly explicit.", relatedIds: [13, 11, 4, 5, 46], rarity: 'common', canUnlockArt: false },
    { id: 33, name: "Mutual Masturbation", cardType: "Practice/Kink", visualHandle: "common_mutualmast", primaryElement: "I", elementScores: { A: 5, I: 5, S: 6, P: 4, C: 4, R: 5 }, briefDescription: "Partners masturbating together.", detailedDescription: "Two or more partners engaging in simultaneous masturbation, potentially watching or manually stimulating each other to orgasm.", relatedIds: [1, 18, 19], rarity: 'common', canUnlockArt: false },
    { id: 46, name: "Compliments / Praise", cardType: "Practice/Kink", visualHandle: "common_praise", primaryElement: "P", elementScores: { A: 4, I: 5, S: 2, P: 7, C: 4, R: 5 }, briefDescription: "Verbal affirmation during intimacy.", detailedDescription: "Using positive verbal feedback, compliments, or praise related to appearance, performance, or desirability to enhance connection, confidence, and arousal.", relatedIds: [32, 15, 50], rarity: 'common', canUnlockArt: false },
    { id: 47, name: "Eye Contact", cardType: "Practice/Kink", visualHandle: "common_eyecontact", primaryElement: "P", elementScores: { A: 5, I: 6, S: 2, P: 7, C: 3, R: 6 }, briefDescription: "Intense gazing during intimacy.", detailedDescription: "Maintaining direct and often intense eye contact during sexual activity to heighten intimacy, connection, vulnerability, or sometimes power dynamics.", relatedIds: [3, 15], rarity: 'common', canUnlockArt: false },
    { id: 48, name: "Holding Hands", cardType: "Practice/Kink", visualHandle: "common_handholding", primaryElement: "P", elementScores: { A: 3, I: 4, S: 3, P: 5, C: 1, R: 4 }, briefDescription: "Simple physical connection.", detailedDescription: "The simple act of clasping hands, often signifying affection, connection, comfort, or partnership, whether during sexual activity or not.", relatedIds: [2, 31], rarity: 'common', canUnlockArt: false },
    { id: 49, name: "Shared Fantasy Talk", cardType: "Practice/Kink", visualHandle: "common_fantasytalk", primaryElement: "C", elementScores: { A: 5, I: 5, S: 3, P: 6, C: 6, R: 5 }, briefDescription: "Verbally sharing fantasies.", detailedDescription: "Partners verbally describing their sexual fantasies to each other, either as a form of mutual arousal or to build towards potential future play.", relatedIds: [32, 14], rarity: 'common', canUnlockArt: false },
    { id: 50, name: "Validation Seeking", cardType: "Psychological/Goal", visualHandle: "common_validation", primaryElement: "P", elementScores: { A: 5, I: 6, S: 5, P: 7, C: 4, R: 5 }, briefDescription: "Sex motivated by feeling desired.", detailedDescription: "Engaging in sexual activity partly or primarily motivated by the need to feel desired, attractive, skilled, or validated by a partner's reactions or praise.", relatedIds: [18, 46], rarity: 'common', canUnlockArt: false },
    { id: 51, name: "Stress Relief Focus", cardType: "Psychological/Goal", visualHandle: "common_stressrelief", primaryElement: "P", elementScores: { A: 4, I: 4, S: 5, P: 6, C: 3, R: 4 }, briefDescription: "Using sex to unwind/relax.", detailedDescription: "Utilizing sexual activity, including orgasm, primarily as a means to release tension, reduce stress, and achieve a state of relaxation.", relatedIds: [1], rarity: 'common', canUnlockArt: false },
    { id: 52, name: "Heterosexuality", cardType: "Orientation", visualHandle: "common_hetero", primaryElement: "A", elementScores: { A: 7, I: 5, S: 5, P: 5, C: 5, R: 5 }, briefDescription: "Attraction to different gender(s).", detailedDescription: "Sexual and/or romantic attraction primarily to individuals of a different gender identity than one's own.", relatedIds: [53, 54, 55], rarity: 'common', canUnlockArt: false },
    { id: 53, name: "Homosexuality", cardType: "Orientation", visualHandle: "common_homo", primaryElement: "A", elementScores: { A: 7, I: 5, S: 5, P: 5, C: 5, R: 5 }, briefDescription: "Attraction to same gender(s).", detailedDescription: "Sexual and/or romantic attraction primarily to individuals of the same gender identity as one's own.", relatedIds: [52, 54, 55], rarity: 'common', canUnlockArt: false },
    { id: 54, name: "Bisexuality", cardType: "Orientation", visualHandle: "common_bi", primaryElement: "A", elementScores: { A: 6, I: 5, S: 5, P: 5, C: 5, R: 5 }, briefDescription: "Attraction to two or more genders.", detailedDescription: "Sexual and/or romantic attraction to more than one gender identity, potentially including one's own and different genders.", relatedIds: [52, 53, 55], rarity: 'common', canUnlockArt: false },
    { id: 55, name: "Pansexuality", cardType: "Orientation", visualHandle: "common_pan", primaryElement: "A", elementScores: { A: 5, I: 5, S: 5, P: 5, C: 5, R: 5 }, briefDescription: "Attraction regardless of gender.", detailedDescription: "Sexual and/or romantic attraction to individuals regardless of their gender identity or presentation. Attraction may be focused on other qualities.", relatedIds: [52, 53, 54], rarity: 'common', canUnlockArt: false },
    { id: 56, name: "Quickie", cardType: "Practice/Kink", visualHandle: "common_quickie", primaryElement: "I", elementScores: { A: 6, I: 6, S: 6, P: 3, C: 2, R: 4 }, briefDescription: "Brief, often spontaneous sex.", detailedDescription: "A short sexual encounter, often focused on achieving orgasm quickly due to time constraints or a desire for immediate gratification.", relatedIds: [1, 24], rarity: 'common', canUnlockArt: false },

    // --- Uncommon Concepts --- (~25)
    { id: 4, name: "Dominance (Psychological)", cardType: "Identity/Role", visualHandle: "uncommon_dom", primaryElement: "I", elementScores: { A: 6, I: 9, S: 5, P: 8, C: 7, R: 6 }, briefDescription: "Taking psychological control.", detailedDescription: "Focuses on the mental and emotional aspects of control within a dynamic, potentially involving commands, tasks, setting rules, or managing a partner's experience.", relatedIds: [5, 6, 11, 30, 38], rarity: 'uncommon', canUnlockArt: true, visualHandleUnlocked: "uncommon_dom_art" },
    { id: 5, name: "Submission (Psychological)", cardType: "Identity/Role", visualHandle: "uncommon_sub", primaryElement: "I", elementScores: { A: 6, I: 1, S: 5, P: 8, C: 5, R: 6 }, briefDescription: "Yielding psychological control.", detailedDescription: "Focuses on the mental and emotional aspects of yielding control, finding pleasure or fulfillment in obedience, service, following directions, or surrendering decisions.", relatedIds: [4, 6, 17, 10, 12], rarity: 'uncommon', canUnlockArt: true, visualHandleUnlocked: "uncommon_sub_art" },
    { id: 6, name: "Switching", cardType: "Identity/Role", visualHandle: "uncommon_switch", primaryElement: "I", elementScores: { A: 6, I: 5, S: 6, P: 7, C: 6, R: 6 }, briefDescription: "Moving between D/s roles.", detailedDescription: "Describes the ability and desire to fluidly shift between dominant and submissive roles or energies within sexual encounters, enjoying aspects of both leading and following.", relatedIds: [4, 5], rarity: 'uncommon', canUnlockArt: false },
    { id: 7, name: "Impact Play (Light)", cardType: "Practice/Kink", visualHandle: "uncommon_impact_light", primaryElement: "S", elementScores: { A: 5, I: 6, S: 6, P: 5, C: 4, R: 5 }, briefDescription: "Spanking, light slapping/flogging.", detailedDescription: "Involves activities like spanking, slapping, or using paddles/floggers lightly, primarily for pleasurable stinging sensations or rhythmic input rather than intense pain.", relatedIds: [8, 9, 4, 5], rarity: 'uncommon', canUnlockArt: true, visualHandleUnlocked: "uncommon_impact_light_art" },
    { id: 10, name: "Service Submission", cardType: "Psychological/Goal", visualHandle: "uncommon_service", primaryElement: "I", elementScores: { A: 5, I: 2, S: 4, P: 7, C: 4, R: 6 }, briefDescription: "Pleasure from serving a partner.", detailedDescription: "A form of submission focused on deriving pleasure and fulfillment from performing acts of service for a partner, which may be sexual or non-sexual within a dynamic.", relatedIds: [5, 4, 11], rarity: 'uncommon', canUnlockArt: false },
    { id: 13, name: "Role-Playing (Scenario)", cardType: "Practice/Kink", visualHandle: "uncommon_roleplay", primaryElement: "C", elementScores: { A: 6, I: 6, S: 5, P: 6, C: 8, R: 6 }, briefDescription: "Adopting characters/personas.", detailedDescription: "Involves adopting specific character archetypes (e.g., doctor/patient, teacher/student, captor/captive) or personas to create a narrative framework for sexual interaction.", relatedIds: [14, 30, 21, 39], rarity: 'uncommon', canUnlockArt: true, visualHandleUnlocked: "uncommon_roleplay_art" },
    { id: 15, name: "Deep Emotional Intimacy", cardType: "Psychological/Goal", visualHandle: "uncommon_intimacy", primaryElement: "P", elementScores: { A: 7, I: 5, S: 4, P: 9, C: 5, R: 7 }, briefDescription: "Seeking profound connection.", detailedDescription: "Places a high value on using sexual expression as a way to build and deepen emotional connection, trust, vulnerability, and mutual understanding.", relatedIds: [2, 3, 22, 29, 47], rarity: 'uncommon', canUnlockArt: true, visualHandleUnlocked: "uncommon_intimacy_art" },
    { id: 18, name: "Exhibitionism", cardType: "Identity/Role", visualHandle: "uncommon_exhibit", primaryElement: "I", elementScores: { A: 6, I: 7, S: 5, P: 7, C: 6, R: 5 }, briefDescription: "Pleasure from being watched.", detailedDescription: "Finding sexual arousal and pleasure in the act of being watched by others during sexual activity, potentially involving performance or revealing oneself.", relatedIds: [19, 12, 34, 50], rarity: 'uncommon', canUnlockArt: false },
    { id: 19, name: "Voyeurism", cardType: "Identity/Role", visualHandle: "uncommon_voyeur", primaryElement: "A", elementScores: { A: 7, I: 2, S: 3, P: 6, C: 5, R: 3 }, briefDescription: "Pleasure from watching others.", detailedDescription: "Finding sexual arousal and pleasure primarily from the act of watching others engage in sexual activity, often without their knowledge (consensual voyeurism involves negotiated watching).", relatedIds: [18, 12, 34], rarity: 'uncommon', canUnlockArt: false },
    { id: 26, name: "Open Relationship", cardType: "Relationship Style", visualHandle: "uncommon_openrel", primaryElement: "R", elementScores: { A: 6, I: 5, S: 6, P: 5, C: 5, R: 7 }, briefDescription: "Primary couple + outside sex.", detailedDescription: "A relationship structure, typically involving a primary couple, where partners agree that one or both may have sexual relationships with other people, often with rules about emotional involvement.", relatedIds: [24, 25, 27, 35], rarity: 'uncommon', canUnlockArt: false },
    { id: 28, name: "Asexuality", cardType: "Orientation", visualHandle: "uncommon_ace", primaryElement: "A", elementScores: { A: 0, I: 3, S: 2, P: 3, C: 3, R: 4 }, briefDescription: "Little or no sexual attraction.", detailedDescription: "Characterized by a persistent lack of sexual attraction towards any gender. Asexual individuals may still experience romantic attraction, desire intimacy, or engage in sexual activity for various reasons.", relatedIds: [29, 36], rarity: 'uncommon', canUnlockArt: false },
    { id: 29, name: "Demisexuality", cardType: "Orientation", visualHandle: "uncommon_demi", primaryElement: "A", elementScores: { A: 3, I: 4, S: 4, P: 8, C: 5, R: 5 }, briefDescription: "Attraction requires emotional bond.", detailedDescription: "A sexual orientation where an individual only develops sexual attraction after forming a strong emotional connection with someone.", relatedIds: [15, 28, 22], rarity: 'uncommon', canUnlockArt: false },
    { id: 34, name: "Group Sex", cardType: "Practice/Kink", visualHandle: "uncommon_group", primaryElement: "R", elementScores: { A: 6, I: 6, S: 7, P: 5, C: 4, R: 8 }, briefDescription: "Sex involving 3+ people.", detailedDescription: "Engaging in sexual acts with three or more people simultaneously. Dynamics can vary widely from casual encounters to structured orgies or polyamorous group play.", relatedIds: [18, 19, 25, 26, 27, 35], rarity: 'uncommon', canUnlockArt: false },
    { id: 35, name: "Swinging", cardType: "Relationship Style", visualHandle: "uncommon_swing", primaryElement: "R", elementScores: { A: 5, I: 5, S: 6, P: 4, C: 4, R: 7 }, briefDescription: "Couples swapping partners for sex.", detailedDescription: "A lifestyle where committed couples consensually engage in sexual activities with other couples or individuals, often at parties or planned events, typically with an emphasis on recreational sex over deep emotional connection with outside partners.", relatedIds: [26, 24, 34], rarity: 'uncommon', canUnlockArt: false },
    { id: 36, name: "Aromanticism", cardType: "Orientation", visualHandle: "uncommon_aro", primaryElement: "A", elementScores: { A: 2, I: 3, S: 3, P: 4, C: 4, R: 3 }, briefDescription: "Little or no romantic attraction.", detailedDescription: "Characterized by a lack of romantic attraction. Aromantic individuals may still experience sexual attraction (allosexual) or not (aro/ace), and may desire platonic partnerships or other relationship structures.", relatedIds: [28, 27], rarity: 'uncommon', canUnlockArt: false },
    { id: 37, name: "Sensory Deprivation (Light)", cardType: "Practice/Kink", visualHandle: "uncommon_sensdep", primaryElement: "S", elementScores: { A: 4, I: 3, S: 7, P: 6, C: 5, R: 5 }, briefDescription: "Reducing sight/sound (blindfolds).", detailedDescription: "Using blindfolds, hoods, earplugs, or other methods to significantly reduce or eliminate one or more senses, often heightening remaining senses, increasing vulnerability, or creating a specific psychological state. Light deprivation focuses on temporary reduction.", relatedIds: [9, 17, 5, 57], rarity: 'uncommon', canUnlockArt: false },
    { id: 38, name: "Teasing & Denial", cardType: "Practice/Kink", visualHandle: "uncommon_denial", primaryElement: "P", elementScores: { A: 6, I: 7, S: 7, P: 8, C: 7, R: 6 }, briefDescription: "Building arousal, withholding orgasm.", detailedDescription: "A form of psychological play and power exchange where one partner intentionally builds the other's arousal close to orgasm but repeatedly denies release, often increasing desperation and reinforcing control dynamics.", relatedIds: [4, 5, 11, 9, 44], rarity: 'uncommon', canUnlockArt: true, visualHandleUnlocked: "uncommon_denial_art" },
    { id: 39, name: "Age Play", cardType: "Practice/Kink", visualHandle: "uncommon_ageplay", primaryElement: "C", elementScores: { A: 5, I: 6, S: 4, P: 7, C: 8, R: 6 }, briefDescription: "Role-playing different ages.", detailedDescription: "Consensual role-playing where participants adopt personas and behaviors associated with ages different from their own (e.g., caregiver/little, teacher/student). Focus is typically on the dynamic and psychological state, not actual age differences.", relatedIds: [13, 4, 5, 10, 58], rarity: 'uncommon', canUnlockArt: false },
    { id: 40, name: "Primal Play", cardType: "Practice/Kink", visualHandle: "uncommon_primal", primaryElement: "I", elementScores: { A: 5, I: 8, S: 7, P: 6, C: 3, R: 5 }, briefDescription: "Instinctive, animalistic interaction.", detailedDescription: "A style of play involving raw, instinctive, and often non-verbal interaction, tapping into animalistic urges like chasing, biting, growling, nuzzling, or struggling. Can range from playful to intense.", relatedIds: [4, 5, 9, 7, 8], rarity: 'uncommon', canUnlockArt: true, visualHandleUnlocked: "uncommon_primal_art"},
    { id: 57, name: "Sensory Enhancement", cardType: "Practice/Kink", visualHandle: "uncommon_sensenh", primaryElement: "S", elementScores: { A: 4, I: 5, S: 7, P: 5, C: 4, R: 5}, briefDescription: "Heightening specific senses.", detailedDescription: "Using techniques or tools (like feathers, ice, vibration, specific sounds/scents) specifically to amplify or focus on particular sensory inputs, often after a period of deprivation or contrast.", relatedIds: [2, 37, 7, 9], rarity: 'uncommon', canUnlockArt: false },
    { id: 58, name: "Caregiver/Little Dynamics", cardType: "Psychological/Goal", visualHandle: "uncommon_cgl", primaryElement: "P", elementScores: { A: 5, I: 7, S: 4, P: 8, C: 6, R: 7 }, briefDescription: "Nurturing/dependent role-play.", detailedDescription: "A dynamic, often linked with Age Play, involving one partner taking on a nurturing, authoritative Caregiver role (DD/lg, MD/lb, etc.) and the other adopting a more dependent, vulnerable Little role.", relatedIds: [39, 4, 5, 10, 15], rarity: 'uncommon', canUnlockArt: false },
    { id: 59, name: "Platonic Partnership / QPR", cardType: "Relationship Style", visualHandle: "uncommon_qpr", primaryElement: "R", elementScores: { A: 3, I: 4, S: 3, P: 7, C: 5, R: 6 }, briefDescription: "Deep non-romantic commitment.", detailedDescription: "Queerplatonic Relationships (QPRs) or other committed platonic partnerships involve a deep bond, commitment, and intimacy that transcends typical friendship norms but is not inherently romantic or sexual.", relatedIds: [22, 36, 15], rarity: 'uncommon', canUnlockArt: false },
    { id: 60, name: "Sapiosexuality", cardType: "Orientation", visualHandle: "uncommon_sapio", primaryElement: "A", elementScores: { A: 7, I: 5, S: 3, P: 6, C: 8, R: 5 }, briefDescription: "Attraction to intelligence.", detailedDescription: "Finding intelligence to be the most sexually attractive feature in a person, potentially outweighing physical appearance or other factors.", relatedIds: [49], rarity: 'uncommon', canUnlockArt: false },
    { id: 61, name: "Body Worship", cardType: "Practice/Kink", visualHandle: "uncommon_bodyworship", primaryElement: "P", elementScores: { A: 6, I: 4, S: 6, P: 8, C: 3, R: 6 }, briefDescription: "Reverential focus on partner's body.", detailedDescription: "Expressing adoration or reverence for a partner's body through acts like kissing, licking, massaging, or simply admiring specific parts, often within a power exchange dynamic.", relatedIds: [5, 10, 12, 62], rarity: 'uncommon', canUnlockArt: false },
    { id: 62, name: "Foot Fetish / Podophilia", cardType: "Orientation", visualHandle: "uncommon_footfetish", primaryElement: "A", elementScores: { A: 8, I: 4, S: 7, P: 5, C: 3, R: 4 }, briefDescription: "Sexual interest focused on feet.", detailedDescription: "A specific paraphilia involving sexual arousal derived from feet. This can include kissing, licking, massaging, or incorporating feet into other sexual acts.", relatedIds: [61, 12], rarity: 'uncommon', canUnlockArt: false }, // Example paraphilia

    // --- Rare Concepts --- (~15)
    { id: 8, name: "Impact Play (Heavy)", cardType: "Practice/Kink", visualHandle: "rare_impact_heavy", primaryElement: "S", elementScores: { A: 5, I: 7, S: 9, P: 7, C: 4, R: 6 }, briefDescription: "Intense impact, pain/marks focus.", detailedDescription: "Utilizes implements like canes, whips, heavy paddles, or fists to deliver strong, often painful sensations. Focus can be on endurance, marking, or the psychological aspects of receiving intense impact.", relatedIds: [7, 9, 4, 5, 44], rarity: 'rare', canUnlockArt: true, visualHandleUnlocked: "rare_impact_heavy_art" },
    { id: 9, name: "Pain Play (Non-Impact)", cardType: "Practice/Kink", visualHandle: "rare_pain", primaryElement: "S", elementScores: { A: 4, I: 6, S: 8, P: 7, C: 5, R: 6 }, briefDescription: "Pinching, biting, wax, needles.", detailedDescription: "Focuses on creating intense sensations through means other than direct impact, such as pinching, biting, scratching, temperature play (wax, ice), clamps, or potentially needles (use extreme caution).", relatedIds: [7, 8, 16, 17, 37, 44], rarity: 'rare', canUnlockArt: true, visualHandleUnlocked: "rare_pain_art" },
    { id: 11, name: "Command/Control Dynamics", cardType: "Psychological/Goal", visualHandle: "rare_control", primaryElement: "I", elementScores: { A: 6, I: 9, S: 5, P: 8, C: 8, R: 6 }, briefDescription: "Explicit orders given/obeyed.", detailedDescription: "A power dynamic characterized by one partner giving clear commands or instructions and the other partner deriving pleasure or fulfillment from obeying them precisely.", relatedIds: [4, 5, 10, 30, 38, 45], rarity: 'rare', canUnlockArt: true, visualHandleUnlocked: "rare_control_art" },
    { id: 12, name: "Objectification Play", cardType: "Psychological/Goal", visualHandle: "rare_object", primaryElement: "P", elementScores: { A: 7, I: 4, S: 6, P: 8, C: 6, R: 5 }, briefDescription: "Consensually treating/being treated as object.", detailedDescription: "Consensual play involving focusing on a person's body or specific body parts as the primary source of pleasure or utility, potentially dehumanizing them temporarily within the agreed scene.", relatedIds: [4, 5, 20, 18, 19, 45, 61], rarity: 'rare', canUnlockArt: false },
    { id: 14, name: "Fantasy Immersion", cardType: "Cognitive", visualHandle: "rare_fantasy", primaryElement: "C", elementScores: { A: 5, I: 3, S: 4, P: 7, C: 9, R: 3 }, briefDescription: "Deep focus on internal narrative.", detailedDescription: "Prioritizes internal mental experience, elaborate fantasy worlds, or complex narratives over external reality during sexual encounters. Arousal is heavily dependent on the mental construct.", relatedIds: [13, 29, 41, 42], rarity: 'rare', canUnlockArt: true, visualHandleUnlocked: "rare_fantasy_art" },
    { id: 16, name: "Rope Bondage (Shibari/Kinbaku)", cardType: "Practice/Kink", visualHandle: "rare_rope", primaryElement: "S", elementScores: { A: 6, I: 7, S: 8, P: 7, C: 6, R: 6 }, briefDescription: "Aesthetic/restrictive rope tying.", detailedDescription: "An art form and practice involving tying a partner with rope, focusing on aesthetic patterns, nerve pressure, physical restriction, and the psychological state induced by the tie.", relatedIds: [9, 17, 4, 5, 44], rarity: 'rare', canUnlockArt: true, visualHandleUnlocked: "rare_rope_art" },
    { id: 17, name: "Restriction/Helplessness", cardType: "Psychological/Goal", visualHandle: "rare_restrict", primaryElement: "P", elementScores: { A: 5, I: 3, S: 7, P: 9, C: 5, R: 5 }, briefDescription: "Arousal from restraint/surrender.", detailedDescription: "Deriving significant arousal from the sensation of being physically restrained (via ropes, cuffs, etc.) and the associated psychological state of helplessness or surrender.", relatedIds: [16, 5, 9, 37, 44], rarity: 'rare', canUnlockArt: false },
    { id: 20, name: "Latex/Material Fetish", cardType: "Orientation", visualHandle: "rare_latex", primaryElement: "A", elementScores: { A: 9, I: 5, S: 8, P: 6, C: 5, R: 4 }, briefDescription: "Attraction focused on materials.", detailedDescription: "A specific fetish where sexual arousal is strongly and primarily triggered by the sight, feel, sound, or smell of particular materials like latex, leather, PVC, rubber, silk, etc.", relatedIds: [12, 21, 42], rarity: 'rare', canUnlockArt: true, visualHandleUnlocked: "rare_latex_art" },
    { id: 21, name: "Uniform/Clothing Fetish", cardType: "Orientation", visualHandle: "rare_uniform", primaryElement: "A", elementScores: { A: 8, I: 6, S: 4, P: 6, C: 6, R: 5 }, briefDescription: "Specific clothing as arousal trigger.", detailedDescription: "A fetish where sexual arousal is significantly and primarily triggered by specific types of clothing, such as uniforms (military, medical, school), costumes, or specific garments (lingerie, suits).", relatedIds: [13, 20, 12], rarity: 'rare', canUnlockArt: false },
    { id: 25, name: "Polyamory", cardType: "Relationship Style", visualHandle: "rare_poly", primaryElement: "R", elementScores: { A: 6, I: 6, S: 5, P: 7, C: 6, R: 8 }, briefDescription: "Multiple loving relationships.", detailedDescription: "The practice of, or desire for, intimate relationships with more than one partner, with the informed consent of all partners involved. Often involves emotional intimacy with multiple people.", relatedIds: [15, 26, 27, 34, 59], rarity: 'rare', canUnlockArt: true, visualHandleUnlocked: "rare_poly_art" },
    { id: 27, name: "Relationship Anarchy", cardType: "Relationship Style", visualHandle: "rare_ra", primaryElement: "R", elementScores: { A: 6, I: 5, S: 5, P: 6, C: 7, R: 9 }, briefDescription: "Rejects rules/hierarchies.", detailedDescription: "A philosophy and relationship style that rejects societal norms and imposed rules regarding relationships. Each relationship is unique and defined by the individuals involved, without inherent hierarchy.", relatedIds: [25, 26, 36, 59], rarity: 'rare', canUnlockArt: false },
    { id: 30, name: "High Protocol D/s", cardType: "Practice/Kink", visualHandle: "rare_protocol", primaryElement: "I", elementScores: { A: 6, I: 8, S: 6, P: 8, C: 9, R: 7 }, briefDescription: "Highly structured power exchange.", detailedDescription: "A style of Dominance and submission characterized by significant structure, formal rules, rituals, specific forms of address, and often pre-negotiated expectations for behavior within the dynamic.", relatedIds: [4, 5, 11, 13, 38], rarity: 'rare', canUnlockArt: true, visualHandleUnlocked: "rare_protocol_art" },
    { id: 41, name: "Erotic Hypnosis / Mind Control Play", cardType: "Practice/Kink", visualHandle: "rare_hypno", primaryElement: "C", elementScores: { A: 5, I: 7, S: 3, P: 8, C: 9, R: 6 }, briefDescription: "Using suggestion/perceived control.", detailedDescription: "Consensual play involving altered states of consciousness, hypnotic suggestion, triggers, or the *illusion* of one partner controlling the other's mind or actions for erotic purposes. Safety and consent are paramount.", relatedIds: [14, 4, 5, 11, 45], rarity: 'rare', canUnlockArt: false },
    { id: 42, name: "Transformation Fetish", cardType: "Orientation", visualHandle: "rare_transform", primaryElement: "C", elementScores: { A: 7, I: 4, S: 5, P: 7, C: 8, R: 4 }, briefDescription: "Arousal from transformation themes.", detailedDescription: "A fetish centered on the concept of transformation, which can include physical changes (e.g., into animals, objects, different genders), mental changes (e.g., bimbofication, personality alteration), or forced changes within a power dynamic.", relatedIds: [20, 21, 12, 41, 14], rarity: 'rare', canUnlockArt: false },
    { id: 43, name: "Medical Play", cardType: "Practice/Kink", visualHandle: "rare_medical", primaryElement: "C", elementScores: { A: 5, I: 6, S: 7, P: 7, C: 7, R: 6 }, briefDescription: "Role-playing medical scenarios.", detailedDescription: "Consensual role-playing involving medical themes, settings, or equipment. Can range from simple doctor/patient scenarios to more clinical interactions involving mock examinations, implements (speculums, needles - potentially real/blunt), restraints, or power dynamics inherent in medical settings.", relatedIds: [13, 9, 17, 4, 5], rarity: 'rare', canUnlockArt: false },
    { id: 44, name: "Edge Play", cardType: "Practice/Kink", visualHandle: "rare_edge", primaryElement: "S", elementScores: { A: 5, I: 6, S: 9, P: 8, C: 5, R: 6 }, briefDescription: "Pushing boundaries near limits.", detailedDescription: "Activities that intentionally push physical, psychological, or emotional boundaries close to perceived limits. Often involves negotiation, high trust, and managing real or perceived risk (e.g., breath play, knife play, extreme sensation, fear play). Requires significant caution, expertise, and communication.", relatedIds: [8, 9, 16, 17, 37, 38, 41], rarity: 'rare', canUnlockArt: false },
    { id: 45, name: "Humiliation / Degradation", cardType: "Psychological/Goal", visualHandle: "rare_humiliation", primaryElement: "P", elementScores: { A: 5, I: 7, S: 4, P: 9, C: 6, R: 6 }, briefDescription: "Pleasure from embarrassment/degradation.", detailedDescription: "Consensual play where one partner derives pleasure from performing or receiving acts or words intended to cause embarrassment, shame, or degradation. Can range from light teasing to intense psychological scenarios. Consent and aftercare are critical.", relatedIds: [4, 5, 10, 11, 12, 38, 41], rarity: 'rare', canUnlockArt: false },
    { id: 63, name: "Breath Play", cardType: "Practice/Kink", visualHandle: "rare_breath", primaryElement: "S", elementScores: { A: 4, I: 7, S: 9, P: 8, C: 4, R: 6 }, briefDescription: "Restricting airflow for sensation.", detailedDescription: "Consensual practice involving the restriction of airflow (erotic asphyxiation) to create intense physical sensations and altered mental states. Carries significant risks and requires extreme caution, knowledge, and trust.", relatedIds: [44, 17, 9, 5], rarity: 'rare', canUnlockArt: false },
    { id: 64, name: "CNC (Consensual Non-Consent)", cardType: "Practice/Kink", visualHandle: "rare_cnc", primaryElement: "C", elementScores: { A: 6, I: 7, S: 7, P: 8, C: 9, R: 6 }, briefDescription: "Role-playing lack of consent.", detailedDescription: "Consensual role-playing scenarios where participants act out a scene involving simulated non-consent or coercion (e.g., simulated rape fantasy, abduction). Requires meticulous negotiation, clear boundaries, safewords, and trust.", relatedIds: [13, 4, 5, 17, 44], rarity: 'rare', canUnlockArt: false },

];

// --- Utility Maps ---
const elementKeyToFullName = { A: "Attraction", I: "Interaction", S: "Sensory", P: "Psychological", C: "Cognitive", R: "Relational" };

// --- Questionnaire Data --- (Restored)
const questionnaireGuided = {
    "Attraction": [
        { qId: "a1", type: "slider", text: "How specific are the triggers for your sexual attraction? (e.g., Very broad vs. Very specific types/situations)", minValue: 0, maxValue: 10, defaultValue: 5, minLabel: "Very Broad / Few Specifics", maxLabel: "Very Specific / Narrow Focus", scoreWeight: 1.0 },
        { qId: "a2", type: "checkbox", text: "Which factors significantly contribute to your initial attraction? (Select up to 2)", options: [ { value: "Physical Appearance/Body Type", points: 0.5 }, { value: "Gender Identity/Presentation", points: 0.5 }, { value: "Personality/Demeanor", points: 0.0 }, { value: "Intellect/Wit", points: 0.5 }, { value: "Signs of Power/Confidence", points: 1.0 }, { value: "Signs of Vulnerability/Submissiveness", points: 1.0 }, { value: "Emotional Connection (Pre-existing)", points: -1.0 }, { value: "Specific Clothing/Materials", points: 1.5 }, { value: "Context/Situation (e.g., role-play)", points: 1.0 } ], scoreWeight: 1.0, maxChoices: 2 },
        { qId: "a3", type: "radio", text: "How important is an emotional bond BEFORE feeling sexual attraction?", options: [ { value: "Essential", points: -2.0 }, { value: "Helpful, but not required", points: -0.5 }, { value: "Neutral / Varies", points: 0 }, { value: "Generally unimportant", points: 1.0 } ], scoreWeight: 1.0 }
    ],
    "Interaction": [
         { qId: "i1", type: "slider", text: "In sexual interactions, where do you naturally find yourself on the spectrum of leading vs. following?", minValue: 0, maxValue: 10, defaultValue: 5, minLabel: "Strongly Following / Receiving", maxLabel: "Strongly Leading / Directing", scoreWeight: 1.0 },
         { qId: "i2", type: "checkbox", text: "Which interaction styles or roles feel most appealing? (Select up to 2)", options: [ { value: "Taking Charge / Dominating", points: 1.5 }, { value: "Guiding / Being Attentive (Top/Caregiver)", points: 1.0 }, { value: "Collaborating / Switching Roles", points: 0 }, { value: "Following Directions / Submitting", points: -1.5 }, { value: "Serving / Pleasing Partner", points: -1.0 }, { value: "Performing / Being Watched", points: 0.5 }, { value: "Playful / Teasing", points: 0.0 } ], scoreWeight: 1.0, maxChoices: 2 },
         { qId: "i3", type: "radio", text: "Do you prefer clear power dynamics or more equal footing?", options: [ { value: "Clear Power Difference (D/s)", points: 1.5 }, { value: "Subtle Power Dynamics", points: 0.5 }, { value: "Equal Footing / Collaborative", points: -1.0 }, { value: "Varies Greatly / No Preference", points: 0 } ], scoreWeight: 1.0 }
    ],
    "Sensory": [
        { qId: "s1", type: "slider", text: "How important is the intensity and variety of physical sensation to your arousal?", minValue: 0, maxValue: 10, defaultValue: 5, minLabel: "Low Importance / Subtle Preferred", maxLabel: "High Importance / Intensity Craved", scoreWeight: 1.0 },
        { qId: "s2", type: "checkbox", text: "Which types of physical sensations are particularly appealing? (Select up to 2)", options: [ { value: "Gentle Touch / Caressing / Warmth", points: -1.0 }, { value: "Firm Pressure / Massage / Hugging", points: 0.0 }, { value: "Sharp / Stinging (Spanking, Biting)", points: 1.5 }, { value: "Burning / Temperature Play (Wax, Ice)", points: 1.5 }, { value: "Restriction / Binding / Helplessness", points: 1.0 }, { value: "Specific Textures (Latex, Silk, Rope)", points: 1.0 }, { value: "Vibration / Electrostimulation", points: 1.5 } ], scoreWeight: 1.0, maxChoices: 2 },
        { qId: "s3", type: "radio", text: "How do you feel about incorporating pain or extreme sensations?", options: [ { value: "Strongly Drawn To It", points: 2.0 }, { value: "Open To Exploring It", points: 1.0 }, { value: "Neutral / Indifferent", points: 0 }, { value: "Prefer to Avoid It", points: -1.0 }, { value: "Strongly Averse To It", points: -2.0 } ], scoreWeight: 1.0 }
     ],
    "Psychological": [
        { qId: "p1", type: "slider", text: "How much is your sexuality tied to fulfilling deeper emotional or psychological needs (beyond physical pleasure)?", minValue: 0, maxValue: 10, defaultValue: 5, minLabel: "Very Little / Primarily Physical", maxLabel: "Very Much / Primary Driver", scoreWeight: 1.0 },
        { qId: "p2", type: "checkbox", text: "Which psychological needs does sex MOST effectively help you meet? (Select up to 2)", options: [ { value: "Deep Connection / Intimacy / Trust", points: 1.5 }, { value: "Power / Control (Giving or Receiving)", points: 1.5 }, { value: "Validation / Feeling Desired", points: 1.0 }, { value: "Escape / Stress Relief / Forgetting", points: 0.5 }, { value: "Catharsis / Emotional Release", points: 1.0 }, { value: "Self-Exploration / Identity Expression", points: 0.5 }, { value: "Security / Comfort / Nurturing", points: 0.0 }, { value: "Simple Fun / Recreation", points: -1.0 } ], scoreWeight: 1.0, maxChoices: 2 },
        { qId: "p3", type: "radio", text: "Does sex feel incomplete if a specific psychological need isn't addressed?", options: [ { value: "Yes, Often", points: 1.5 }, { value: "Sometimes", points: 0.5 }, { value: "Rarely", points: -0.5 }, { value: "Never", points: -1.5 } ], scoreWeight: 1.0 }
     ],
    "Cognitive": [
        { qId: "c1", type: "slider", text: "How important is mental engagement (fantasy, scenarios, intellect) during sex?", minValue: 0, maxValue: 10, defaultValue: 5, minLabel: "Not Important / Prefer Presence", maxLabel: "Very Important / Mentally Driven", scoreWeight: 1.0 },
        { qId: "c2", type: "checkbox", text: "Which mental aspects significantly enhance your arousal? (Select up to 2)", options: [ { value: "Detailed Internal Fantasies", points: 1.5 }, { value: "Specific Role-Playing Scenarios", points: 1.5 }, { value: "Dirty Talk / Erotic Language", points: 1.0 }, { value: "Intellectual Banter / Mind Games", points: 1.0 }, { value: "Understanding Partner's Psychology", points: 0.5 }, { value: "Anticipation / Pre-Planned Scenes", points: 1.0 }, { value: "Being Fully 'In the Moment'", points: -1.5 } ], scoreWeight: 1.0, maxChoices: 2 },
        { qId: "c3", type: "radio", text: "Do you prefer spontaneous encounters or more planned/scripted ones?", options: [ { value: "Strongly Prefer Planned/Scripted", points: 1.5 }, { value: "Lean Towards Planned", points: 0.5 }, { value: "No Real Preference / Mix", points: 0 }, { value: "Lean Towards Spontaneous", points: -0.5 }, { value: "Strongly Prefer Spontaneous", points: -1.5 } ], scoreWeight: 1.0 }
    ],
    "Relational": [
         { qId: "r1", type: "slider", text: "What is your ideal relationship structure regarding number of partners?", minValue: 0, maxValue: 10, defaultValue: 3, minLabel: "Strictly One (Monogamy) / Solitary", maxLabel: "Multiple Partners / Fluidity", scoreWeight: 1.0 },
         { qId: "r2", type: "checkbox", text: "Which relationship contexts feel most comfortable or desirable? (Select up to 2)", options: [ { value: "Solitary / Self-Exploration", points: -1.5 }, { value: "Deeply Committed Monogamous Pair", points: -1.0 }, { value: "Casual Dating / Friends With Benefits", points: 0.5 }, { value: "Open Relationship (Primary + Others)", points: 1.0 }, { value: "Polyamory (Multiple Equal Relationships)", points: 1.5 }, { value: "Group Sex Scenarios", points: 1.0 }, { value: "Anonymous Encounters", points: 0.5 } ], scoreWeight: 1.0, maxChoices: 2 },
         { qId: "r3", type: "radio", text: "How important is relationship 'hierarchy' (e.g., having a 'primary' partner)?", options: [ { value: "Very Important / Need a Primary", points: -1.0 }, { value: "Somewhat Important / Prefer Hierarchy", points: -0.5 }, { value: "Neutral / Depends on Relationship", points: 0 }, { value: "Prefer Non-Hierarchical", points: 1.0 }, { value: "Strongly Against Hierarchy (Anarchy)", points: 1.5 } ], scoreWeight: 1.0 }
    ]
};

// --- Reflection Prompts (with Dissonance) ---
const reflectionPrompts = {
    "Attraction": [ /* ... */ ], "Interaction": [ /* ... */ ], "Sensory": [ /* ... */ ], "Psychological": [ /* ... */ ], "Cognitive": [ /* ... */ ], "Relational": [ /* ... */ ],
    "Dissonance": [
        { id: "pD1", text: "This concept seems quite different from your current profile. What aspect of it intrigues you or makes you curious?" },
        { id: "pD2", text: "Exploring unfamiliar territory can be revealing. What potential does engaging with this concept hold for you, even if it feels challenging?" },
        { id: "pD3", text: "Sometimes, what we resist holds a key. Is there an underlying need or desire this concept touches upon that you haven't fully acknowledged?" },
        { id: "pD4", text: "How might integrating or understanding this concept broaden your perspective on your own sexuality or that of others?" }
    ]
}; // (Ensure previous element prompts are filled in)

// --- Rituals & Milestones Data (Updated Rewards) ---
const dailyRituals = [
    { id: "dr01", description: "Perform your Daily Meditation (Free Research).", reward: { type: "insight", amount: 2 }, track: { action: "freeResearch", count: 1, period: "daily" } },
    { id: "dr02", description: "Add 1 Concept to your Grimoire.", reward: { type: "insight", amount: 3 }, track: { action: "addToGrimoire", count: 1, period: "daily" } },
    { id: "dr03", description: "Complete a Reflection Prompt.", reward: { type: "insight", amount: 5 }, track: { action: "completeReflection", count: 1, period: "daily" } },
    { id: "dr04", description: "Focus on a new Concept.", reward: { type: "insight", amount: 4 }, track: { action: "markFocus", count: 1, period: "daily" } },
];

const milestones = [
    // Early Game & Discovery
    { id: "ms01", description: "First Concept Added!", reward: { type: "insight", amount: 5 }, track: { state: "discoveredConcepts.size", threshold: 1 } },
    { id: "ms02", description: "Curator I: Added 5 Concepts", reward: { type: "insight", amount: 10 }, track: { state: "discoveredConcepts.size", threshold: 5 } },
    { id: "ms15", description: "Curator II: Added 15 Concepts", reward: { type: "increaseFocusSlots", amount: 1 }, track: { state: "discoveredConcepts.size", threshold: 15 } }, // 5->6 slots
    { id: "ms25", description: "Curator III: Added 25 Concepts", reward: { type: "insight", amount: 20 }, track: { state: "discoveredConcepts.size", threshold: 25 } },
    { id: "ms40", description: "Grand Curator: Added 40 Concepts", reward: { type: "increaseFocusSlots", amount: 1 }, track: { state: "discoveredConcepts.size", threshold: 40 } }, // 6->7 slots? (adjust thresholds)

    // Focus & Tapestry
    { id: "ms03", description: "First Focus Concept Marked", reward: { type: "insight", amount: 8 }, track: { state: "focusedConcepts.size", threshold: 1 } },
    { id: "ms04", description: "Tapestry Weaver I: Marked 3 Focus Concepts", reward: { type: "attunement", element: "All", amount: 1 }, track: { state: "focusedConcepts.size", threshold: 3 } },
    { id: "ms08", description: "Tapestry Weaver II: Marked 5 Focus Concepts", reward: { type: "increaseFocusSlots", amount: 1 }, track: { state: "focusedConcepts.size", threshold: 5 } }, // Should trigger with initial limit if ms04 met
    { id: "ms18", description: "Tapestry Weaver III: Filled 7 Focus Slots", reward: { type: "insight", amount: 25 }, track: { state: "focusedConcepts.size", threshold: 7 } },

    // Research & Attunement
    { id: "ms05", description: "First Research Conducted", reward: { type: "insight", amount: 5 }, track: { action: "conductResearch", count: 1 } },
    { id: "ms06", description: "Elementalist I: Reached Attunement 10 in one Element", reward: { type: "insight", amount: 15 }, track: { state: "elementAttunement", threshold: 10, condition: "any" } },
    { id: "ms13", description: "Well Rounded: Attunement 5+ in all Elements", reward: { type: "insight", amount: 25 }, track: { state: "elementAttunement", threshold: 5, condition: "all" } },
    { id: "ms20", description: "Elementalist II: Reached Attunement 50 in one Element", reward: { type: "increaseFocusSlots", amount: 1 }, track: { state: "elementAttunement", threshold: 50, condition: "any" } }, // Slot increase
    { id: "ms30", description: "Master Elementalist: Reached Attunement 90 in one Element", reward: { type: "insight", amount: 50 }, track: { state: "elementAttunement", threshold: 90, condition: "any" } },

    // Reflection & Growth
    { id: "ms07", description: "First Reflection Completed", reward: { type: "insight", amount: 5 }, track: { action: "completeReflection", count: 1 } },
    { id: "ms12", description: "Dissonance Embraced: Completed a Dissonance Reflection", reward: { type: "attunement", element: "All", amount: 1.5 }, track: { action: "completeReflectionDissonance", count: 1 } },
    { id: "ms22", description: "Self-Awareness: Completed 5 Reflections", reward: { type: "insight", amount: 20 }, track: { action: "completeReflection", count: 5 } }, // Needs counter for total reflections
    { id: "ms23", description: "Growth Mindset: Allowed Score Nudge after Reflection", reward: { type: "insight", amount: 10 }, track: { action: "scoreNudgeApplied", count: 1 } }, // Needs tracking in handleConfirmReflection

    // Specific Discoveries & Evolution
    { id: "ms09", description: "Attuned to Interaction: Reached Attunement 20 in Interaction", reward: { type: "discoverCard", cardId: 6 }, track: { state: "elementAttunement", element: "I", threshold: 20 } },
    { id: "ms10", description: "Deep Thinker: Reached Attunement 20 in Cognitive", reward: { type: "discoverCard", cardId: 14 }, track: { state: "elementAttunement", element: "C", threshold: 20 } },
    { id: "ms11", description: "First Art Evolution", reward: { type: "insight", amount: 20 }, track: { action: "evolveArt", count: 1 } },
    { id: "ms21", description: "Rare Find: Discovered a Rare Concept Card", reward: { type: "insight", amount: 15 }, track: { action: "discoverRareCard", count: 1 } }, // Needs tracking in research/add

    // Add more milestones for higher counts, other actions, etc.
];
